In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, GRU
import copy
import time
from sklearn.preprocessing import StandardScaler
import random

In [2]:
df = pd.read_csv("../Data/data_(8-8).csv")
sc = StandardScaler()

In [3]:
X = df.iloc[:800, :8].values
y = df.iloc[:800, 8:16].values
X = sc.fit_transform(X)
X_test = df.iloc[800:1000, :8].values
y_test = df.iloc[800:1000, 8:16].values
X_test = sc.fit_transform(X_test)

In [4]:
X1= np.reshape(X, (X.shape[0],X.shape[1],1))
y1= np.reshape(y, (y.shape[0], y.shape[1]))
X2= np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
y2= np.reshape(y_test, (y_test.shape[0], y_test.shape[1]))

In [5]:
model = Sequential()
model.add(GRU(units=24, input_shape=(8,1), activation="tanh"))
model.add(Dense(8, activation="sigmoid")) 
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
gru (GRU)                    (None, 24)                1944      
_________________________________________________________________
dense (Dense)                (None, 8)                 200       
Total params: 2,144
Trainable params: 2,144
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.fit(X1, y1, epochs = 100,batch_size=64)

Epoch 1/100
13/13 [==============================] - 2s 4ms/step - loss: 0.2478 - accuracy: 0.0338
Epoch 2/100
13/13 [==============================] - 0s 4ms/step - loss: 0.2386 - accuracy: 0.0950
Epoch 3/100
13/13 [==============================] - 0s 4ms/step - loss: 0.2262 - accuracy: 0.0850
Epoch 4/100
13/13 [==============================] - 0s 4ms/step - loss: 0.2072 - accuracy: 0.0150
Epoch 5/100
13/13 [==============================] - 0s 5ms/step - loss: 0.1837 - accuracy: 0.0000e+00
Epoch 6/100
13/13 [==============================] - 0s 6ms/step - loss: 0.1747 - accuracy: 0.0000e+00
Epoch 7/100
13/13 [==============================] - 0s 5ms/step - loss: 0.1716 - accuracy: 0.1425
Epoch 8/100
13/13 [==============================] - 0s 4ms/step - loss: 0.1699 - accuracy: 0.2562
Epoch 9/100
13/13 [==============================] - 0s 4ms/step - loss: 0.1686 - accuracy: 0.2438
Epoch 10/100
13/13 [==============================] - 0s 4ms/step - loss: 0.1672 - accuracy: 0.2237
E

13/13 [==============================] - 0s 4ms/step - loss: 0.0500 - accuracy: 0.3525
Epoch 83/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0491 - accuracy: 0.3575
Epoch 84/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0488 - accuracy: 0.3587
Epoch 85/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0489 - accuracy: 0.3537
Epoch 86/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0484 - accuracy: 0.3562
Epoch 87/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0476 - accuracy: 0.3500
Epoch 88/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0470 - accuracy: 0.3537
Epoch 89/100
13/13 [==============================] - 0s 4ms/step - loss: 0.0470 - accuracy: 0.3550
Epoch 90/100
13/13 [==============================] - 0s 5ms/step - loss: 0.0464 - accuracy: 0.3512
Epoch 91/100
13/13 [==============================] - 0s 5ms/step - loss: 0.0461 - accuracy: 0.3550
Epoch 92/100


In [32]:
accuracy = 0
for i in range(X1.shape[0]):
    output = model.predict(X1[i:i+1,:,:]).reshape(-1)
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y1[i,j]):
            condition = False
            break
    if condition:
        accuracy += 1
accuracy = accuracy / X1.shape[0] * 100

In [33]:
accuracy

83.5

In [34]:
accuracy_test = 0
for i in range(X2.shape[0]):
    output = model.predict(X2[i:i+1,:,:]).reshape(-1)
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y2[i,j]):
            condition = False
            break
    if condition:
        accuracy_test += 1
accuracy_test = accuracy_test / X2.shape[0] * 100

In [35]:
accuracy_test

83.5

In [36]:
units=24
W = model.get_weights()[0]
U = model.get_weights()[1]
b = model.get_weights()[2]
wy = model.get_weights()[3].T
by = model.get_weights()[4]

wz = W[:, :units]
wr = W[:, units: units * 2]
wh = W[:, units * 2: units * 3]

uz = U[:, :units]
ur = U[:, units: units * 2]
uh = U[:, units * 2: units * 3]

bwz = b[0:1,:units]
bwr = b[0:1,units: units * 2]
bwh = b[0:1,units * 2: units * 3]
buz = b[1:2,:units]
bur = b[1:2,units: units * 2]
buh = b[1:2,units * 2: units * 3]

In [37]:
by.shape

(8,)

In [38]:
bwz

array([[-0.55716854, -0.2407887 , -0.3579678 , -0.53846663, -0.11937902,
        -0.47072354, -0.25911075, -0.401315  , -0.24627899, -0.21211413,
        -0.6278655 , -0.7319144 , -0.25333947, -0.34698862, -0.6329625 ,
        -0.32239702, -0.17472805, -0.43110535, -0.1683506 , -0.2729127 ,
        -0.46602765, -0.45709682, -0.51483744, -0.359297  ]],
      dtype=float32)

In [39]:
buz

array([[-0.55716854, -0.2407887 , -0.3579678 , -0.53846663, -0.11937902,
        -0.47072354, -0.25911075, -0.401315  , -0.24627899, -0.21211413,
        -0.6278655 , -0.7319144 , -0.25333947, -0.34698862, -0.6329625 ,
        -0.32239702, -0.17472805, -0.43110535, -0.1683506 , -0.2729127 ,
        -0.46602765, -0.45709682, -0.51483744, -0.359297  ]],
      dtype=float32)

In [40]:
bwh

array([[-0.2917159 ,  0.04154516,  0.21379757,  0.19915025,  0.04538475,
        -0.01674505, -0.01115116, -0.03157538,  0.05537773,  0.01483545,
         0.03800354,  0.28794423, -0.00620494, -0.11556424,  0.21294677,
        -0.12830324,  0.06937282,  0.04032767,  0.01789289, -0.10929766,
        -0.16684502,  0.12641086,  0.13663368, -0.19650055]],
      dtype=float32)

In [41]:
buh

array([[-0.29842037,  0.04745157,  0.19814669,  0.20271772,  0.0144861 ,
        -0.00300429,  0.02941675, -0.08641607,  0.07803257,  0.1795018 ,
         0.05194721,  0.25725475, -0.00133649, -0.14373925,  0.24306545,
        -0.21047455,  0.08404038,  0.03198704, -0.01868124, -0.12438022,
        -0.1553798 ,  0.12901877,  0.09042829, -0.22344041]],
      dtype=float32)

In [42]:
wz.shape

(1, 24)

In [43]:
wr.shape

(1, 24)

In [44]:
wh.shape

(1, 24)

In [45]:
wy.shape

(8, 24)

In [46]:
uz.shape

(24, 24)

In [47]:
ur.shape

(24, 24)

In [48]:
uh.shape

(24, 24)

In [49]:
x=X1[0]

In [50]:
x.shape

(8, 1)

In [51]:
xt=x[0].reshape(-1,1)

In [52]:
xt.shape

(1, 1)

In [53]:
from rnn_utils import *

In [54]:
h0 = np.zeros((24,1))

In [61]:
h_next = h0
for i in range(8):
    zt = sigmoid(np.dot(wz.T, x[i].reshape(-1,1)) + bwz.T + np.dot(uz.T, h_next) + buz.T)
    rt = sigmoid(np.dot(wr.T, x[i].reshape(-1,1)) + bwr.T + np.dot(ur.T, h_next) + bur.T)
    nt = np.tanh(np.dot(wh.T, x[i].reshape(-1,1)) + bwh.T + rt*(np.dot(uh.T, h_next) + buh.T))
    h_next = (1-zt)*nt + zt*h_next

In [62]:
h_next.shape

(24, 1)

In [63]:
yt_pred = sigmoid(np.dot(wy, h_next) + by.reshape(-1,1))

In [64]:
yt_pred.reshape(-1)

array([0.12594546, 0.06012547, 0.74261858, 0.0226774 , 0.14860165,
       0.01659037, 0.0514808 , 0.71784677])

In [65]:
model.predict(X1[0:1,:,:])

array([[0.12594551, 0.06012547, 0.7426185 , 0.02267742, 0.14860168,
        0.01659039, 0.05148077, 0.71784663]], dtype=float32)

In [66]:
y1[i]

array([1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)