In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
import copy
import time
from sklearn.preprocessing import StandardScaler
import random

In [2]:
df = pd.read_csv("../Data/data_(8-8).csv")
sc = StandardScaler()

In [3]:
X = df.iloc[:800, :8].values
y = df.iloc[:800, 8:16].values
X = sc.fit_transform(X)
X_test = df.iloc[800:1000, :8].values
y_test = df.iloc[800:1000, 8:16].values
X_test = sc.fit_transform(X_test)

In [4]:
X[0,:]

array([ 1.57075724, -0.39398662, -1.20823935,  0.75271354, -1.48352901,
        0.36607149,  0.40065595,  0.72516916])

In [5]:
X1= np.reshape(X, (X.shape[0], X.shape[1], 1))
y1= np.reshape(y, (y.shape[0], y.shape[1]))

In [6]:
X2= np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
y2= np.reshape(y_test, (y_test.shape[0], y_test.shape[1]))

In [7]:
X1.shape

(800, 8, 1)

In [8]:
y1.shape

(800, 8)

In [9]:
X1[:1,:,:]

array([[[ 1.57075724],
        [-0.39398662],
        [-1.20823935],
        [ 0.75271354],
        [-1.48352901],
        [ 0.36607149],
        [ 0.40065595],
        [ 0.72516916]]])

In [10]:
model = Sequential()
model.add(SimpleRNN(units=24, input_shape=(8,1), activation="tanh"))
model.add(Dense(8, activation="sigmoid")) 
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 24)                624       
_________________________________________________________________
dense (Dense)                (None, 8)                 200       
Total params: 824
Trainable params: 824
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(X1, y1, epochs = 100,batch_size=64)

Epoch 1/100
13/13 [==============================] - 1s 3ms/step - loss: 0.2597 - accuracy: 0.0775
Epoch 2/100
13/13 [==============================] - 0s 3ms/step - loss: 0.2393 - accuracy: 0.1587
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 0.2178 - accuracy: 0.2062
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 0.1929 - accuracy: 0.2188
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 0.1705 - accuracy: 0.1937
Epoch 6/100
13/13 [==============================] - 0s 3ms/step - loss: 0.1540 - accuracy: 0.2138
Epoch 7/100
13/13 [==============================] - 0s 3ms/step - loss: 0.1425 - accuracy: 0.2438
Epoch 8/100
13/13 [==============================] - 0s 3ms/step - loss: 0.1337 - accuracy: 0.2637
Epoch 9/100
13/13 [==============================] - 0s 3ms/step - loss: 0.1269 - accuracy: 0.2713
Epoch 10/100
13/13 [==============================] - 0s 3ms/step - loss: 0.1211 - accuracy: 0.2887
Epoch 11/

13/13 [==============================] - 0s 2ms/step - loss: 0.0409 - accuracy: 0.4487
Epoch 84/100
13/13 [==============================] - 0s 2ms/step - loss: 0.0406 - accuracy: 0.4487
Epoch 85/100
13/13 [==============================] - 0s 2ms/step - loss: 0.0403 - accuracy: 0.4512
Epoch 86/100
13/13 [==============================] - 0s 2ms/step - loss: 0.0404 - accuracy: 0.4412
Epoch 87/100
13/13 [==============================] - 0s 2ms/step - loss: 0.0400 - accuracy: 0.4462
Epoch 88/100
13/13 [==============================] - 0s 2ms/step - loss: 0.0397 - accuracy: 0.4450
Epoch 89/100
13/13 [==============================] - 0s 3ms/step - loss: 0.0394 - accuracy: 0.4475
Epoch 90/100
13/13 [==============================] - 0s 2ms/step - loss: 0.0395 - accuracy: 0.4425
Epoch 91/100
13/13 [==============================] - 0s 3ms/step - loss: 0.0393 - accuracy: 0.4375
Epoch 92/100
13/13 [==============================] - 0s 3ms/step - loss: 0.0390 - accuracy: 0.4350
Epoch 93/100


In [12]:
accuracy = 0
for i in range(X1.shape[0]):
    output = model.predict(X1[i:i+1,:,:]).reshape(-1)
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y1[i,j]):
            condition = False
            break
    if condition:
        accuracy += 1
accuracy = accuracy / X1.shape[0] * 100

In [13]:
accuracy

85.875

In [14]:
accuracy_test = 0
for i in range(X2.shape[0]):
    output = model.predict(X2[i:i+1,:,:]).reshape(-1)
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y2[i,j]):
            condition = False
            break
    if condition:
        accuracy_test += 1
accuracy_test = accuracy_test / X2.shape[0] * 100

In [15]:
accuracy_test

78.0

In [16]:
print(model.get_weights()[0].shape,
model.get_weights()[1].shape,
model.get_weights()[2].shape,
model.get_weights()[3].shape,
model.get_weights()[4].shape)

(1, 24) (24, 24) (24,) (24, 8) (8,)


In [17]:
wx = model.get_weights()[0]
wh = model.get_weights()[1]
bh = model.get_weights()[2]
wy = model.get_weights()[3]
by = model.get_weights()[4]

In [18]:
wx.shape

(1, 24)

In [19]:
weight=[]

In [20]:
weight.append(wx)
weight.append(wh)
weight.append(bh)
weight.append(wy)
weight.append(by)

In [21]:
model_2 = Sequential()
model_2.add(SimpleRNN(units=24, input_shape=(8,1), activation="tanh"))
model_2.add(Dense(8, activation="sigmoid"))
model.compile(loss='mse')

In [22]:
model_2.set_weights(weight)

In [23]:
predicted=model_2.predict(X1[0:1])

In [24]:
predicted.reshape(-1)

array([0.12963796, 0.01688987, 0.8077607 , 0.01421827, 0.14708406,
       0.05389693, 0.0380398 , 0.73082334], dtype=float32)

In [25]:
actual=y1[0]

In [26]:
actual

array([0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [27]:
np.sum(np.power(predicted-actual,2))

0.15269107063801446

In [28]:
class Simple_RNN(object):

    def __init__(self, sizes, steps):
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.wx = np.random.randn(sizes[0], sizes[1])
        self.wh = np.random.randn(sizes[1], sizes[1])
        self.bh = np.random.randn(sizes[1], 1)
        self.wy = np.random.randn(sizes[1], sizes[2])
        self.by = np.random.randn(sizes[2], 1)
        self.h0 = np.zeros(sizes[1])
        self.steps = steps

    def feedforward(self, x):
        h_temp=np.tanh(np.dot(self.wx.T,x[0]) + self.h0 + self.bh.reshape(-1))
        for i in range(self.steps-1):
            h_temp = np.tanh(np.dot( self.wx.T,x[i+1]) + np.dot(self.wh.T,h_temp) + self.bh.reshape(-1))
        result = self.sigmoid(np.dot(self.wy.T,h_temp) + self.by.reshape(-1))
        return result 
    
    def sigmoid(self, z):
        return 1.0/(1.0+np.exp(-z))

    def score(self, X, y):
        total_score=0
        for i in range(X.shape[0]):
            predicted = self.feedforward(X[i])
            actual = y[i]
            total_score += np.sum(np.power(predicted-actual,2))  # mean-squared error
        return total_score/X.shape[0]

    def accuracy(self, X, y):
        accuracy = 0
        for i in range(X.shape[0]):
            output = self.feedforward(X[i])
            condition = True
            for j in range(len(output)):
                output[j] = round(output[j])
            for j in range(len(output)):
                if(output[j]!=y[i][j]):
                    condition = False
                    break
            if condition:
                accuracy += 1
        return accuracy / X.shape[0] * 100

In [29]:
net_size = [1,24,8]
steps = 8

In [30]:
sn = Simple_RNN(net_size,steps)

In [31]:
sn.wx = model.get_weights()[0]
sn.wh = model.get_weights()[1]
sn.bh = model.get_weights()[2]
sn.wy = model.get_weights()[3]
sn.by = model.get_weights()[4]

In [32]:
sn.feedforward(X1[0])

array([0.12963792, 0.01688982, 0.80776074, 0.0142183 , 0.14708398,
       0.05389695, 0.03803985, 0.7308234 ])