In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("data_(18-18).csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 7)  X(4, 5)  \
0       20       20       10       40       30       60       70       80   
1       50       50       50       10       60       40       50       70   
2       60       70       70       30       50       50       50       60   
3       80       70       30       40       30       60       20       10   
4       50       50       50       30       80       10       80       10   

   X(4, 6)  X(4, 7)  ...  Y(4, 6)  Y(4, 7)  Y(5, 6)  Y(5, 8)  Y(5, 9)  \
0       50       30  ...        0        1        0        0        0   
1       30       50  ...        0        0        0        0        0   
2       30       20  ...        0        1        0        0        0   
3       80       60  ...        0        0        0        0        1   
4       50       40  ...        0        0        0        0        1   

   Y(6, 7)  Y(6, 8)  Y(7, 8)  Y(7, 9)  Y(8, 9)  
0        0        0        0        1        0  
1        0        0        0        1        0  
2        0        0        1        0        1  
3        0        0        0        0        0  
4        0        0        0        0        0  

[5 rows x 36 columns]

In [2]:
X = dataset.iloc[:,:18].values
y = dataset.iloc[:,18:36].values

In [3]:
X.shape

(100000, 18)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [5]:
X[1,:]

array([-2.44666995e-03, -1.23868845e-04, -1.20138883e-03, -1.55513717e+00,
        3.88015717e-01, -3.83833713e-01,  1.08772637e-03,  7.75497978e-01,
       -7.72082031e-01, -1.53306146e-03,  7.73999611e-01,  7.73441584e-01,
        1.16131374e+00, -1.15976095e+00,  7.72786728e-01,  3.85793434e-01,
       -1.15997320e+00, -1.54590251e+00])

In [6]:
y[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [8]:
X_test[1,:]

array([-3.89577992e-01, -1.16139429e+00, -1.55138052e+00,  7.76263002e-01,
        1.09112734e-03,  3.90196239e-01,  3.88178962e-01,  3.88097649e-01,
        1.16705276e+00, -7.73856216e-01, -9.45432954e-04,  3.84957072e-01,
        1.16131374e+00, -7.72984447e-01, -3.41918706e-03,  1.54932884e+00,
       -1.54672247e+00, -3.83872681e-01])

In [9]:
y_test[1,:]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [52]:
#Dependencies
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(18, input_dim=18, activation="relu"))
model.add(Dropout(0.5))
# model.add(Dense(18, activation="relu"))
# model.add(Dropout(0.5))
# model.add(Dense(18, activation="relu"))
# model.add(Dropout(0.5))
# model.add(Dense(18, activation="relu"))
# model.add(Dropout(0.2))
model.add(Dense(18, activation="sigmoid"))

In [53]:
binary=tf.keras.metrics.BinaryAccuracy(
    name="binary_accuracy", dtype=None, threshold=0.5
)

In [54]:
model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=[binary])

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
1407/1407 [==============================] - 2s 941us/step - loss: 0.3527 - binary_accuracy: 0.8481
Epoch 2/10
1407/1407 [==============================] - 1s 911us/step - loss: 0.2501 - binary_accuracy: 0.9043
Epoch 3/10
1407/1407 [==============================] - 1s 909us/step - loss: 0.2382 - binary_accuracy: 0.9090
Epoch 4/10
1407/1407 [==============================] - 1s 898us/step - loss: 0.2316 - binary_accuracy: 0.9111
Epoch 5/10
1172/1407 [=======================>......] - ETA: 0s - loss: 0.2295 - binary_accuracy: 0.9117

In [ ]:
loss_and_metrics = model.evaluate(X_test, y_test)

In [ ]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

In [ ]:
y_pred = model.predict(X_train)