In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("data_(18-18).csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 7)  X(4, 5)  \
0       20       20       10       40       30       60       70       80   
1       50       50       50       10       60       40       50       70   
2       60       70       70       30       50       50       50       60   
3       80       70       30       40       30       60       20       10   
4       50       50       50       30       80       10       80       10   

   X(4, 6)  X(4, 7)  ...  Y(4, 6)  Y(4, 7)  Y(5, 6)  Y(5, 8)  Y(5, 9)  \
0       50       30  ...        0        1        0        0        0   
1       30       50  ...        0        0        0        0        0   
2       30       20  ...        0        1        0        0        0   
3       80       60  ...        0        0        0        0        1   
4       50       40  ...        0        0        0        0        1   

   Y(6, 7)  Y(6, 8)  Y(7, 8)  Y(7, 9)  Y(8, 9)  
0        0        0        0        1        0  
1        0        0        0        1        0  
2        0        0        1        0        1  
3        0        0        0        0        0  
4        0        0        0        0        0  

[5 rows x 36 columns]

In [2]:
X = dataset.iloc[:,:18].values
y = dataset.iloc[:,18:36].values

In [3]:
X.shape

(100000, 18)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [5]:
X[1,:]

array([-2.44666995e-03, -1.23868845e-04, -1.20138883e-03, -1.55513717e+00,
        3.88015717e-01, -3.83833713e-01,  1.08772637e-03,  7.75497978e-01,
       -7.72082031e-01, -1.53306146e-03,  7.73999611e-01,  7.73441584e-01,
        1.16131374e+00, -1.15976095e+00,  7.72786728e-01,  3.85793434e-01,
       -1.15997320e+00, -1.54590251e+00])

In [6]:
y[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [8]:
X_test[1,:]

array([-0.38957799,  1.16114655,  0.77388818,  1.55339639,  1.1618649 ,
        1.55124117, -1.54727721, -0.38670301, -0.77208203, -1.54617937,
        1.16147213,  0.38495707, -0.3866144 , -0.77298445,  0.38468377,
       -1.16558711,  1.54727165,  0.0034706 ])

In [9]:
y_test[1,:]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [10]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(18, input_dim=18, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(100, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(18, activation="sigmoid"))

In [11]:
model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=["accuracy", "binary_accuracy"])

In [12]:
model.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.3029 - accuracy: 0.3475 - binary_accuracy: 0.8778
Epoch 2/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.2358 - accuracy: 0.5211 - binary_accuracy: 0.9135
Epoch 3/10
1407/1407 [==============================] - 2s 2ms/step - loss: 0.2288 - accuracy: 0.5366 - binary_accuracy: 0.9169
Epoch 4/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.2256 - accuracy: 0.5393 - binary_accuracy: 0.9183: 0s - loss: 0.2264 - accuracy: 
Epoch 5/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.2242 - accuracy: 0.5359 - binary_accuracy: 0.9189
Epoch 6/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.2229 - accuracy: 0.5307 - binary_accuracy: 0.9193
Epoch 7/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.2222 - accuracy: 0.5398 - binary_accuracy: 0.9194
Epoch 8/10
1407/1407 [==============================] - 2s 2ms/step - lo

In [13]:
loss_and_metrics = model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.1880 - accuracy: 0.6186 - binary_accuracy: 0.9398


In [14]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

2813/2813 [==============================] - 3s 1ms/step - loss: 0.1919 - accuracy: 0.6218 - binary_accuracy: 0.9376
