In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("../Data/data_(18-18).csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 7)  X(4, 5)  \
0       20       20       10       40       30       60       70       80   
1       50       50       50       10       60       40       50       70   
2       60       70       70       30       50       50       50       60   
3       80       70       30       40       30       60       20       10   
4       50       50       50       30       80       10       80       10   

   X(4, 6)  X(4, 7)  ...  Y(4, 6)  Y(4, 7)  Y(5, 6)  Y(5, 8)  Y(5, 9)  \
0       50       30  ...        0        1        0        0        0   
1       30       50  ...        0        0        0        0        0   
2       30       20  ...        0        1        0        0        0   
3       80       60  ...        0        0        0        0        1   
4       50       40  ...        0        0        0        0        1   

   Y(6, 7)  Y(6, 8)  Y(7, 8)  Y(7, 9)  Y(8, 9)  
0        0        0        0        1        0  
1        0        0        0        1        0  
2        0        0        1        0        1  
3        0        0        0        0        0  
4        0        0        0        0        0  

[5 rows x 36 columns]

In [2]:
X = dataset.iloc[:,:18].values
y = dataset.iloc[:,18:36].values

In [3]:
X.shape

(100000, 18)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [5]:
X[1,:]

array([-2.44666995e-03, -1.23868845e-04, -1.20138883e-03, -1.55513717e+00,
        3.88015717e-01, -3.83833713e-01,  1.08772637e-03,  7.75497978e-01,
       -7.72082031e-01, -1.53306146e-03,  7.73999611e-01,  7.73441584e-01,
        1.16131374e+00, -1.15976095e+00,  7.72786728e-01,  3.85793434e-01,
       -1.15997320e+00, -1.54590251e+00])

In [6]:
y[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [8]:
X_test[1,:]

array([ 7.71815974e-01, -1.54848443e+00,  1.16143296e+00, -1.16657048e+00,
       -1.54660723e+00, -7.70848689e-01, -1.16018598e+00,  1.55029863e+00,
        3.91398845e-01, -1.16001779e+00, -3.88417955e-01, -7.80496463e-01,
       -1.54756051e+00,  7.74121570e-01, -7.79625102e-01, -1.55343224e+00,
        2.74591978e-04,  7.78157150e-01])

In [9]:
y_test[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [38]:
#Dependencies
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(18, input_dim=18, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(100, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(18, activation="sigmoid"))

In [39]:
model.compile(loss='mse', optimizer='adam',
              metrics=[tf.keras.metrics.Accuracy(),tf.keras.metrics.BinaryAccuracy(),tf.keras.metrics.CategoricalAccuracy()])

In [40]:
model.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0906 - accuracy: 8.6420e-06 - binary_accuracy: 0.8807 - categorical_accuracy: 0.3756
Epoch 2/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0663 - accuracy: 8.7654e-05 - binary_accuracy: 0.9167 - categorical_accuracy: 0.5449
Epoch 3/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0640 - accuracy: 1.8272e-04 - binary_accuracy: 0.9202 - categorical_accuracy: 0.5608A: 1s - loss: 0.0657 - accuracy: 1.3636e-04 - binary_accuracy: 0.9179 
Epoch 4/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0626 - accuracy: 2.5741e-04 - binary_accuracy: 0.9222 - categorical_accuracy: 0.5700
Epoch 5/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0621 - accuracy: 3.3642e-04 - binary_accuracy: 0.9230 - categorical_accuracy: 0.5621
Epoch 6/10
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0618 - accuracy: 3.9136e-04 - binary_

In [41]:
loss_and_metrics = model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 872us/step - loss: 0.0519 - accuracy: 5.5556e-06 - binary_accuracy: 0.9372 - categorical_accuracy: 0.7056


In [42]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

2813/2813 [==============================] - 2s 849us/step - loss: 0.0510 - accuracy: 0.0000e+00 - binary_accuracy: 0.9390 - categorical_accuracy: 0.7108


In [83]:
pred = model.predict(X_test)

In [84]:
X_test.shape

(10000, 18)

In [85]:
np.around(pred[0])

array([0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0.], dtype=float32)

In [86]:
pred[0]

array([0.00253233, 0.569324  , 0.5827606 , 0.02212909, 0.00113541,
       0.13699582, 0.5916207 , 0.3057902 , 0.08706662, 0.24837902,
       0.01774153, 0.04351613, 0.17731142, 0.04646325, 0.02818805,
       0.08124301, 0.6715165 , 0.14789528], dtype=float32)

In [87]:
pp = []
for pr in pred:
    pp.append(np.around(pr))

In [88]:
pp

[array([0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.], dtype=float32),
 array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.], dtype=float32),
 array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.], dtype=float32),
 array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.], dtype=float32),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0.], dtype=float32),
 array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.], dtype=float32),
 array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.], dtype=float32),
 array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0.], dtype=float32),
 array([1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,

In [89]:
pp2 = []
for pr in y_test:
    pp2.append(np.around(pr))

In [90]:
pp2

[array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
 array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
 array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0], dtype=int64),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),

In [97]:
(pp[2]==pp2[2]).all()

True

In [101]:
c = 0
for i in range(len(pp)):
    for j in range(len(pp[i])):
        if pp[i][j] == pp2[i][j]:
            c+=1
c/(18*10000)

0.9371722222222222

In [102]:
c

168691

In [103]:
t = [1.2, 1.4]
for i in range(len(t)):
    t[i] = round(t[i])
t

[1, 1]