In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("../Data/data_(8-8).csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 5)  X(4, 5)  \
0       90       40       20       70       10       60       60       70   
1       50       70       60       60       80       50       20       40   
2       50       90       80       20       60       70       40       50   
3       20       90       60       60       40       70       30       50   
4       70       70       70       50       40       40       20       60   

   Y(1, 2)  Y(1, 3)  Y(1, 4)  Y(2, 4)  Y(2, 5)  Y(3, 4)  Y(3, 5)  Y(4, 5)  
0        0        0        1        0        0        0        0        1  
1        0        1        0        0        0        0        1        0  
2        1        0        0        0        1        0        0        0  
3        1        0        0        0        1        0        0        0  
4        0        1        0        0        0        0        1        0

In [2]:
X = dataset.iloc[:,:8].values
y = dataset.iloc[:,8:16].values

In [3]:
X.shape

(100000, 8)

In [4]:
y.shape

(100000, 8)

In [5]:
y[0].shape[0]

8

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [7]:
X[1,:]

array([ 0.0029868 ,  0.77637624,  0.39127709,  0.38487583,  1.15719413,
        0.0025869 , -1.16100287, -0.38334669])

In [8]:
y[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [10]:
X_test[1,:]

array([ 7.77773868e-01,  3.89046056e-01, -3.84281555e-01, -1.15811463e+00,
       -1.55456801e+00,  7.77108716e-01,  1.85790185e-04,  1.16424698e+00])

In [11]:
y_test[1,:]

array([0, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [12]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(8, input_dim=8, activation="relu"))
model.add(Dense(8, activation="sigmoid"))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', "binary_accuracy"])

In [14]:
model.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
1407/1407 [==============================] - 2s 969us/step - loss: 0.3399 - accuracy: 0.4805 - binary_accuracy: 0.85200s - loss: 0.4493 - accuracy: 0.3612 - b
Epoch 2/10
1407/1407 [==============================] - 1s 876us/step - loss: 0.1392 - accuracy: 0.6944 - binary_accuracy: 0.9543
Epoch 3/10
1407/1407 [==============================] - 1s 921us/step - loss: 0.1250 - accuracy: 0.7078 - binary_accuracy: 0.95640s - loss: 0.1267 - accuracy: 0.6958
Epoch 4/10
1407/1407 [==============================] - 1s 864us/step - loss: 0.1193 - accuracy: 0.7358 - binary_accuracy: 0.9566
Epoch 5/10
1407/1407 [==============================] - 1s 848us/step - loss: 0.1164 - accuracy: 0.7572 - binary_accuracy: 0.9567
Epoch 6/10
1407/1407 [==============================] - 1s 890us/step - loss: 0.1146 - accuracy: 0.7654 - binary_accuracy: 0.9567
Epoch 7/10
1407/1407 [==============================] - 1s 922us/step - loss: 0.1132 - accuracy: 0.7761 - binary_accuracy: 0.9570
Epoch 8/10
140

In [15]:
loss_and_metrics = model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 929us/step - loss: 0.1123 - accuracy: 0.7849 - binary_accuracy: 0.9578


In [16]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

2813/2813 [==============================] - 2s 674us/step - loss: 0.1088 - accuracy: 0.7816 - binary_accuracy: 0.9579


In [17]:
len(model.layers)

2

In [18]:
X_train[0]

array([-1.15919379e+00,  1.16370642e+00, -7.72060880e-01, -8.71789610e-04,
        7.69799541e-01,  2.58690285e-03, -1.16100287e+00, -1.54404195e+00])

In [19]:
X_test[2].reshape(1,len(X_test[2]))

array([[-1.54658732e+00,  1.55103660e+00,  7.79056419e-01,
        -8.71789610e-04, -4.98964234e-03,  1.55163053e+00,
         7.74311560e-01,  7.77348565e-01]])

In [24]:
pr=model.predict(X_test[0:1,:])

In [25]:
pr

array([[9.99988973e-01, 1.28199845e-05, 3.70271773e-05, 6.70975487e-06,
        9.99965191e-01, 9.36141610e-03, 2.15858221e-04, 1.68681145e-04]],
      dtype=float32)

In [26]:
y_test[0:1,:]

array([[1, 0, 0, 0, 1, 0, 0, 0]], dtype=int64)

In [20]:
pred=model.predict(X_test)

In [21]:
for layer in model.layers:
    print(layer.get_weights())

[array([[-1.9033229 ,  0.9783429 ,  0.62644327, -1.6258036 ,  0.5520173 ,
        -0.48361787,  0.0826516 ,  0.9012289 ],
       [ 0.8588601 ,  0.67512876,  1.0092334 ,  0.4941129 , -1.5357367 ,
         0.58988   ,  0.3686411 , -1.9620153 ],
       [ 1.1022907 , -1.709366  , -1.7898502 ,  0.9673996 ,  0.88152426,
        -0.07643665, -0.44492608,  1.1179835 ],
       [-0.04658457,  0.6548294 ,  0.23367724,  0.9729392 ,  0.22004955,
        -0.5918461 , -0.15742148,  0.47825235],
       [-1.113156  ,  0.9783498 ,  0.39213467, -1.6136272 ,  0.5709271 ,
        -1.3712053 ,  0.58711255,  0.731779  ],
       [ 0.30050892, -0.27665222,  0.9271285 ,  0.21178448,  0.6431671 ,
         0.29705834, -0.08574794, -0.06936794],
       [ 0.68989563,  0.12191362,  1.059512  ,  0.53922373, -1.5958815 ,
         0.724515  ,  0.9200049 , -1.2983816 ],
       [ 0.4132715 , -1.1292484 , -1.5533515 ,  0.9179561 ,  0.9085496 ,
         0.6984505 , -1.4970107 ,  0.52589923]], dtype=float32), array([ 0.1757

In [22]:
import numpy
w=numpy.array([1,2,3])

In [23]:
w.size

3