In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("../Data/data_(8-8).csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 5)  X(4, 5)  \
0       90       40       20       70       10       60       60       70   
1       50       70       60       60       80       50       20       40   
2       50       90       80       20       60       70       40       50   
3       20       90       60       60       40       70       30       50   
4       70       70       70       50       40       40       20       60   

   Y(1, 2)  Y(1, 3)  Y(1, 4)  Y(2, 4)  Y(2, 5)  Y(3, 4)  Y(3, 5)  Y(4, 5)  
0        0        0        1        0        0        0        0        1  
1        0        1        0        0        0        0        1        0  
2        1        0        0        0        1        0        0        0  
3        1        0        0        0        1        0        0        0  
4        0        1        0        0        0        0        1        0

In [2]:
X = dataset.iloc[:,:8].values
y = dataset.iloc[:,8:16].values

In [3]:
X.shape

(100000, 8)

In [4]:
y.shape

(100000, 8)

In [5]:
y[0].shape[0]

8

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [7]:
X[1,:]

array([ 0.0029868 ,  0.77637624,  0.39127709,  0.38487583,  1.15719413,
        0.0025869 , -1.16100287, -0.38334669])

In [8]:
y[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [10]:
X_test[1,:]

array([-1.54658732e+00, -1.54760486e+00, -1.15984021e+00, -1.54386225e+00,
       -4.98964234e-03,  1.16436962e+00,  1.85790185e-04,  1.16424698e+00])

In [11]:
y_test[1,:]

array([1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(8, input_dim=8, activation="relu"))
model.add(Dense(8, activation="sigmoid"))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', "binary_accuracy"])

In [14]:
model.fit(X_train, y_train, epochs=10, batch_size=64)

Epoch 1/10
1407/1407 [==============================] - 2s 981us/step - loss: 0.3210 - accuracy: 0.3270 - binary_accuracy: 0.8699
Epoch 2/10
1407/1407 [==============================] - 1s 981us/step - loss: 0.1409 - accuracy: 0.5046 - binary_accuracy: 0.9545
Epoch 3/10
1407/1407 [==============================] - 1s 1ms/step - loss: 0.1235 - accuracy: 0.6581 - binary_accuracy: 0.9573
Epoch 4/10
1407/1407 [==============================] - 1s 1ms/step - loss: 0.1149 - accuracy: 0.7165 - binary_accuracy: 0.9588
Epoch 5/10
1407/1407 [==============================] - 1s 910us/step - loss: 0.1096 - accuracy: 0.7536 - binary_accuracy: 0.9601
Epoch 6/10
1407/1407 [==============================] - 1s 950us/step - loss: 0.1060 - accuracy: 0.7715 - binary_accuracy: 0.9611
Epoch 7/10
1407/1407 [==============================] - 1s 863us/step - loss: 0.1032 - accuracy: 0.7865 - binary_accuracy: 0.9622
Epoch 8/10
1407/1407 [==============================] - 1s 977us/step - loss: 0.1009 - accurac

In [15]:
loss_and_metrics = model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 757us/step - loss: 0.0948 - accuracy: 0.7949 - binary_accuracy: 0.9632


In [16]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

2813/2813 [==============================] - 2s 789us/step - loss: 0.0959 - accuracy: 0.7974 - binary_accuracy: 0.9638


In [17]:
len(model.layers)

2

In [34]:
X_train[0]

array([ 0.0029868 ,  0.00171587,  1.16683574,  0.77062344, -0.77977883,
       -1.54645672,  1.16137445,  0.77734857])

In [30]:
X_test[2].reshape(1,len(X_test[2]))

array([[ 0.0029868 ,  0.00171587,  0.77905642,  0.38487583, -0.00498964,
        -0.77193491, -1.54806575,  0.39045015]])

In [33]:
pred=model.predict(X_test)

In [18]:
for layer in model.layers:
    print(layer.get_weights())

[array([[ 0.73005176,  0.7322488 ,  0.5753645 ,  0.354886  ,  0.71824694,
         1.049316  , -1.7278045 , -1.8260151 ],
       [-1.2593274 ,  0.28394455,  1.0146409 , -1.1311109 , -1.8310947 ,
         0.70149297,  0.7042009 ,  0.89697605],
       [ 0.60521746, -1.1924655 , -1.5803285 ,  0.8255628 ,  1.0894659 ,
        -1.70878   ,  0.90460855,  0.9870482 ],
       [ 0.47412872,  0.81316555,  0.21848397,  0.08191466,  0.24382232,
        -0.29796907,  0.6710351 , -0.1762534 ],
       [ 0.78835964,  0.7636138 ,  0.6557957 ,  0.24416491,  0.5155286 ,
         0.01962298, -1.8263258 , -1.1091017 ],
       [-0.36841023, -0.16618289,  0.55654645, -1.4582374 ,  0.521393  ,
        -0.18264048,  0.24080896,  0.3183276 ],
       [-1.5537378 , -0.03996497,  1.1256343 ,  0.73723763, -1.3490105 ,
         0.09635422,  0.6941578 ,  0.7782305 ],
       [ 0.87423563, -0.850796  , -1.8497336 , -0.92430854,  0.70489144,
        -0.15601553,  1.03843   ,  0.33033726]], dtype=float32), array([ 0.2632

In [19]:
import numpy
w=numpy.array([1,2,3])

In [20]:
w.size

3