In [1]:
import numpy as np
import pandas as pd
#dataset import
df = pd.read_csv("../Data/data_10_nodes_yen.csv") #You need to change #directory accordingly
df.head()

X(1, 2)  X(1, 5)  X(1, 8)  X(2, 3)  X(2, 8)  X(3, 4)  X(3, 8)  X(3, 9)  \
0       60       60       10       70       80       60       60       80   
1       10       80       20       50       30       40       60       30   
2       10       90       80       40       70       80       40       80   
3       50       60       30       90       40       40       50       60   
4       50       50       20       10       80       60       70       10   

   X(4, 9)  X(4, 10)  ...  Y4(4, 10)  Y4(5, 6)  Y4(5, 8)  Y4(6, 7)  Y4(6, 8)  \
0       90        50  ...          1         0         0         0         0   
1       90        40  ...          0         0         0         0         0   
2       80        70  ...          0         0         1         0         0   
3       20        20  ...          1         1         0         0         0   
4       60        40  ...          1         0         0         0         0   

   Y4(6, 9)  Y4(7, 9)  Y4(7, 10)  Y4(8, 9)  Y4(9, 10)  
0         0         0          0         1          0  
1         0         0          0         0          1  
2         0         0          0         1          1  
3         1         0          0         0          0  
4         0         0          0         0          0  

[5 rows x 95 columns]

In [2]:
X = df.iloc[:,:19].values
y = df.iloc[:,19:].values

In [3]:
X.shape

(200000, 19)

In [4]:
y.shape

(200000, 76)

In [5]:
from sklearn.model_selection import train_test_split
X1,X2,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [6]:
X2[1]

array([70, 80, 10, 40, 60, 30, 70, 30, 70, 60, 90, 40, 80, 30, 10, 10, 50,
       40, 20], dtype=int64)

In [7]:
y_test[1]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X1)
X_test= sc.fit_transform(X2)

In [9]:
X_train = np.repeat(X_train[:, np.newaxis, : ], 4, axis=1)
X_train.shape

(180000, 4, 19)

In [10]:
X_test = np.repeat(X_test[:, np.newaxis, : ], 4, axis=1)
X_test.shape

(20000, 4, 19)

In [11]:
y_train[0]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
y_train_2 = np.reshape(y_train,(y_train.shape[0], 4, 19))
y_train_2.shape

(180000, 4, 19)

In [13]:
y_train_2[0]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [14]:
y_test_2 = np.reshape(y_test,(y_test.shape[0], 4, 19))
y_test_2.shape

(20000, 4, 19)

In [15]:
X2[1,:]

array([70, 80, 10, 40, 60, 30, 70, 30, 70, 60, 90, 40, 80, 30, 10, 10, 50,
       40, 20], dtype=int64)

In [16]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,SimpleRNN,TimeDistributed
# Neural network
model = Sequential()
model.add(SimpleRNN(128, input_shape=(4, 19), 
                    return_sequences=True))
model.add(SimpleRNN(128, return_sequences=True))
model.add(SimpleRNN(128, return_sequences=True))
model.add(SimpleRNN(128, return_sequences=True))
model.add(TimeDistributed(Dense(128, activation='relu')))
model.add(Dense(19, activation='sigmoid'))

In [17]:
model.compile(loss='BinaryCrossentropy', optimizer='adam')

In [18]:
model.fit(X_train, y_train_2, epochs=100, batch_size=64)

Epoch 1/100
2813/2813 [==============================] - 22s 7ms/step - loss: 0.2830
Epoch 2/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.2336
Epoch 3/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.2138
Epoch 4/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.2000
Epoch 5/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1898
Epoch 6/100
2813/2813 [==============================] - 21s 8ms/step - loss: 0.1824
Epoch 7/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1762
Epoch 8/100
2813/2813 [==============================] - 19s 7ms/step - loss: 0.1710
Epoch 9/100
2813/2813 [==============================] - 19s 7ms/step - loss: 0.1662
Epoch 10/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1625
Epoch 11/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1586
Epoch 12/100
2813/2813 [==============================] - 20s 7

2813/2813 [==============================] - 20s 7ms/step - loss: 0.1142
Epoch 97/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1137
Epoch 98/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1137
Epoch 99/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1136
Epoch 100/100
2813/2813 [==============================] - 20s 7ms/step - loss: 0.1133


In [19]:
len(model.layers)

6

In [20]:
pred=model.predict(X_train)

5625/5625 [==============================] - 13s 2ms/step


In [21]:
pred.shape

(180000, 4, 19)

In [22]:
pred[0]

array([[5.5958481e-06, 9.9990660e-01, 4.7544298e-05, 1.3357044e-06,
        1.2887036e-06, 3.4789216e-06, 5.5792648e-06, 1.4110283e-06,
        1.9613432e-05, 5.1316779e-06, 3.6437114e-04, 9.9978328e-01,
        6.1008100e-06, 8.1010265e-05, 2.1543815e-04, 6.9390298e-06,
        6.6444454e-07, 9.9979872e-01, 9.9998623e-01],
       [3.4444402e-05, 9.9973273e-01, 9.4547519e-05, 1.6753840e-05,
        2.9001626e-06, 2.6980231e-06, 1.0374409e-05, 1.0687628e-05,
        4.9137661e-06, 4.1573926e-06, 9.9906170e-01, 9.2079432e-04,
        1.7177027e-04, 9.8750925e-06, 9.9873555e-01, 2.6300101e-04,
        8.8342422e-05, 9.8016148e-04, 9.9983126e-01],
       [8.5917237e-04, 6.8147634e-03, 9.9136126e-01, 1.8508814e-03,
        2.1921140e-04, 1.5846170e-02, 1.7170247e-02, 3.4858105e-03,
        1.0020202e-03, 7.7726478e-03, 6.2460611e-03, 9.1869291e-03,
        3.3574313e-04, 4.2451755e-03, 7.2921868e-03, 6.7478773e-04,
        2.4933473e-04, 9.8228365e-01, 9.9398524e-01],
       [9.7394641e-04,

In [23]:
y_train_2[0]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [24]:
edges = [[1, 2], [1, 5], [1, 8], [2, 3], [2, 8], [3, 4], [3, 8], [3, 9], [4, 9], [4, 10], [5, 6], [5, 8], [6, 7], [6, 8], [6, 9], [7, 9], [7, 10], [8, 9],[9, 10]]

In [25]:
import copy
def cost_path(x,y):
    cost = 0
    path = []
    for i in range(19):
        if y[i]==1:
            path.append(edges[i])
            cost+= x[i]
    if(len(path)!=0):
        path_2 = copy.deepcopy(path)
        path_nodes = [1]
        if(path[0][0]!=1):
            cost = 0
        else:
            path_nodes.append(path[0][1])
            del path_2[0]
            condition = True
            while(len(path_2)!=0 and condition):
                condition = False
                for i in range(len(path_2)):
                    if(path_nodes[-1] in path_2[i]):
                        path_2[i].remove(path_nodes[-1])
                        path_nodes.append(path_2[i][0])
                        path_2.pop(i)
                        condition = True
                        break
        if(path_nodes[-1]!=10 or len(path_2)!=0):
            cost = 0
    else:
        cost = 0
    return cost

In [26]:
cost_path(X1[1],y_train[1])

80

In [38]:
accuracy = 0
for i in range(pred.shape[0]):
    output = copy.deepcopy(pred[i][2])
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    if(i%10000 == 0):
        print(output, cost_path(X1[i],output))
    if(cost_path(X1[i],output) != cost_path(X1[i],y_train_2[i][2])):
        condition = False
    if condition:
        accuracy += 1
accuracy / pred.shape[0] * 100

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.] 180
[1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 150
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.] 0
[1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 120
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.] 140
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.] 110
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.] 160
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.] 170
[0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 140
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.] 0
[1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 140
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.] 130
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.] 130
[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.] 150
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0.] 150
[1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 

78.6288888888889

In [39]:
pred_test=model.predict(X_test)

625/625 [==============================] - 2s 3ms/step


In [40]:
accuracy_test = 0
for i in range(pred_test.shape[0]):
    output = copy.deepcopy(pred_test[i][2])
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    if(cost_path(X2[i],output)!=cost_path(X2[i],y_test_2[i][2])):
        condition = False
    if condition:
        accuracy_test += 1
accuracy_test / pred_test.shape[0] * 100

75.19500000000001

In [41]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 4, 128)            18944     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 4, 128)            32896     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 4, 128)            32896     
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 4, 128)            32896     
                                                                 
 time_distributed (TimeDistr  (None, 4, 128)           16512     
 ibuted)                                                         
                                                                 
 dense_1 (Dense)             (None, 4, 19)             2451      
                                                        