In [1]:
import numpy as np
import pandas as pd
#dataset import
df = pd.read_csv("../Data/data_10_nodes_yen.csv") #You need to change #directory accordingly
df.head()

X(1, 2)  X(1, 5)  X(1, 8)  X(2, 3)  X(2, 8)  X(3, 4)  X(3, 8)  X(3, 9)  \
0       60       60       10       70       80       60       60       80   
1       10       80       20       50       30       40       60       30   
2       10       90       80       40       70       80       40       80   
3       50       60       30       90       40       40       50       60   
4       50       50       20       10       80       60       70       10   

   X(4, 9)  X(4, 10)  ...  Y4(4, 10)  Y4(5, 6)  Y4(5, 8)  Y4(6, 7)  Y4(6, 8)  \
0       90        50  ...          1         0         0         0         0   
1       90        40  ...          0         0         0         0         0   
2       80        70  ...          0         0         1         0         0   
3       20        20  ...          1         1         0         0         0   
4       60        40  ...          1         0         0         0         0   

   Y4(6, 9)  Y4(7, 9)  Y4(7, 10)  Y4(8, 9)  Y4(9, 10)  
0         0         0          0         1          0  
1         0         0          0         0          1  
2         0         0          0         1          1  
3         1         0          0         0          0  
4         0         0          0         0          0  

[5 rows x 95 columns]

In [2]:
X = df.iloc[:,:57].values
y = df.iloc[:,57:76].values

In [3]:
X.shape

(200000, 57)

In [4]:
y.shape

(200000, 19)

In [5]:
from sklearn.model_selection import train_test_split
X1,X2,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [6]:
X2[1]

array([60, 90, 90, 80, 60, 80, 50, 50, 70, 80, 10, 60, 70, 80, 90, 20, 10,
       90, 40,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,
        0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  1,  0], dtype=int64)

In [7]:
y_test[1]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
      dtype=int64)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X1)
X_test= sc.fit_transform(X2)

In [9]:
X2[1,:]

array([60, 90, 90, 80, 60, 80, 50, 50, 70, 80, 10, 60, 70, 80, 90, 20, 10,
       90, 40,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,
        0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  1,  0], dtype=int64)

In [10]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(128, input_dim=57, activation="relu"))
# model.add(Dropout(0.2))
model.add(Dense(128, activation="relu"))
# model.add(Dropout(0.2))
model.add(Dense(19, activation="sigmoid"))

In [11]:
model.compile(loss='BinaryCrossentropy', optimizer='adam')

In [12]:
model.fit(X_train, y_train, epochs=100, batch_size=64)

Epoch 1/100
2813/2813 [==============================] - 7s 2ms/step - loss: 0.3177
Epoch 2/100
2813/2813 [==============================] - 6s 2ms/step - loss: 0.2547
Epoch 3/100
2813/2813 [==============================] - 6s 2ms/step - loss: 0.2293
Epoch 4/100
2813/2813 [==============================] - 6s 2ms/step - loss: 0.2120
Epoch 5/100
2813/2813 [==============================] - 7s 2ms/step - loss: 0.1991
Epoch 6/100
2813/2813 [==============================] - 8s 3ms/step - loss: 0.1896
Epoch 7/100
2813/2813 [==============================] - 7s 2ms/step - loss: 0.1819
Epoch 8/100
2813/2813 [==============================] - 7s 2ms/step - loss: 0.1753
Epoch 9/100
2813/2813 [==============================] - 7s 2ms/step - loss: 0.1695
Epoch 10/100
2813/2813 [==============================] - 9s 3ms/step - loss: 0.1645
Epoch 11/100
2813/2813 [==============================] - 9s 3ms/step - loss: 0.1598
Epoch 12/100
2813/2813 [==============================] - 7s 2ms/step - lo

2813/2813 [==============================] - 6s 2ms/step - loss: 0.0897
Epoch 98/100
2813/2813 [==============================] - 6s 2ms/step - loss: 0.0896
Epoch 99/100
2813/2813 [==============================] - 5s 2ms/step - loss: 0.0890
Epoch 100/100
2813/2813 [==============================] - 5s 2ms/step - loss: 0.0889


In [13]:
loss_and_metrics = model.evaluate(X_test, y_test)

625/625 [==============================] - 1s 1ms/step - loss: 0.1209


In [14]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

5625/5625 [==============================] - 6s 1ms/step - loss: 0.0854


In [15]:
len(model.layers)

3

In [16]:
pred=model.predict(X_train)

5625/5625 [==============================] - 6s 1ms/step


In [17]:
pred.shape[0]

180000

In [18]:
pred[0]

array([2.3697942e-02, 9.9398851e-01, 1.6315394e-06, 2.3048366e-05,
       3.2735698e-02, 7.4398420e-05, 1.3003169e-04, 3.4493246e-06,
       7.8124427e-03, 7.2246226e-03, 9.9117529e-01, 2.5719501e-05,
       9.9996036e-01, 6.0411855e-03, 2.1031572e-07, 9.3112814e-01,
       6.9626018e-02, 3.1883815e-07, 2.7969134e-01], dtype=float32)

In [19]:
y_train[0]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1],
      dtype=int64)

In [20]:
edges = [[1, 2], [1, 5], [1, 8], [2, 3], [2, 8], [3, 4], [3, 8], [3, 9], [4, 9], [4, 10], [5, 6], [5, 8], [6, 7], [6, 8], [6, 9], [7, 9], [7, 10], [8, 9],[9, 10]]

In [21]:
import copy
def cost_path(x,y):
    cost = 0
    path = []
    for i in range(19):
        if y[i]==1:
            path.append(edges[i])
            cost+= x[i]
    if(len(path)!=0):
        path_2 = copy.deepcopy(path)
        path_nodes = [1]
        if(path[0][0]!=1):
            cost = 0
        else:
            path_nodes.append(path[0][1])
            del path_2[0]
            condition = True
            while(len(path_2)!=0 and condition):
                condition = False
                for i in range(len(path_2)):
                    if(path_nodes[-1] in path_2[i]):
                        path_2[i].remove(path_nodes[-1])
                        path_nodes.append(path_2[i][0])
                        path_2.pop(i)
                        condition = True
                        break
        if(path_nodes[-1]!=10 or len(path_2)!=0):
            cost = 0
    else:
        cost = 0
    return cost

In [22]:
cost_path(X1[1],y_train[1])

170

In [23]:
accuracy = 0
for i in range(pred.shape[0]):
    output = copy.deepcopy(pred[i])
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    if(i%10000 == 0):
        print(output, cost_path(X1[i],output))
    if(cost_path(X1[i],output) != cost_path(X1[i],y_train[i])):
        condition = False
    if condition:
        accuracy += 1
accuracy / pred.shape[0] * 100

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0.] 0
[0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.] 140
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.] 170
[1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 180
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0.] 140
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1.] 160
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.] 110
[1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 140
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.] 0
[0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 150
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.] 160
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.] 110
[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.] 110
[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.] 120
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.] 180
[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.] 

78.66277777777778

In [24]:
pred_test=model.predict(X_test)

625/625 [==============================] - 1s 2ms/step


In [25]:
accuracy_test = 0
for i in range(pred_test.shape[0]):
    output = pred_test[i].copy()
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    if(cost_path(X2[i],output)!=cost_path(X2[i],y_test[i])):
        condition = False
    if condition:
        accuracy_test += 1
accuracy_test / pred_test.shape[0] * 100

74.82

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               7424      
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 19)                2451      
                                                                 
Total params: 26,387
Trainable params: 26,387
Non-trainable params: 0
_________________________________________________________________
