In [1]:
import numpy as np
import pandas as pd
#dataset import
df = pd.read_csv("../Data/data_10_nodes_yen.csv") #You need to change #directory accordingly
df.head()

X(1, 2)  X(1, 5)  X(1, 8)  X(2, 3)  X(2, 8)  X(3, 4)  X(3, 8)  X(3, 9)  \
0       60       60       10       70       80       60       60       80   
1       10       80       20       50       30       40       60       30   
2       10       90       80       40       70       80       40       80   
3       50       60       30       90       40       40       50       60   
4       50       50       20       10       80       60       70       10   

   X(4, 9)  X(4, 10)  ...  Y4(4, 10)  Y4(5, 6)  Y4(5, 8)  Y4(6, 7)  Y4(6, 8)  \
0       90        50  ...          1         0         0         0         0   
1       90        40  ...          0         0         0         0         0   
2       80        70  ...          0         0         1         0         0   
3       20        20  ...          1         1         0         0         0   
4       60        40  ...          1         0         0         0         0   

   Y4(6, 9)  Y4(7, 9)  Y4(7, 10)  Y4(8, 9)  Y4(9, 10)  
0         0         0          0         1          0  
1         0         0          0         0          1  
2         0         0          0         1          1  
3         1         0          0         0          0  
4         0         0          0         0          0  

[5 rows x 95 columns]

In [2]:
edges = [[1, 2], [1, 5], [1, 8], [2, 3], [2, 8], [3, 4], [3, 8], [3, 9], [4, 9], [4, 10], [5, 6], [5, 8], [6, 7], [6, 8], [6, 9], [7, 9], [7, 10], [8, 9],[9, 10]]

In [3]:
number_edges = 19
number_steps = 4
start_node = 1
end_node = 10

In [4]:
X = df.iloc[:200000,:number_edges].values
y = df.iloc[:200000,number_edges:].values

In [5]:
X.shape

(200000, 19)

In [6]:
y.shape

(200000, 76)

In [7]:
from sklearn.model_selection import train_test_split
X1,X2,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [8]:
X2[1]

array([20, 70, 90, 20, 60, 40, 90, 70, 10, 60, 60, 80, 10, 20, 60, 20, 70,
       40, 20], dtype=int64)

In [9]:
y_test[1]

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X1)
X_test= sc.fit_transform(X2)

In [11]:
X_train = np.repeat(X_train[:, np.newaxis, : ], number_steps, axis=1)
X_train.shape

(180000, 4, 19)

In [12]:
X_test = np.repeat(X_test[:, np.newaxis, : ], number_steps, axis=1)
X_test.shape

(20000, 4, 19)

In [13]:
y_train[0]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [14]:
y_train_2 = np.reshape(y_train,(y_train.shape[0], number_steps, number_edges))
y_train_2.shape

(180000, 4, 19)

In [15]:
y_train_2[0]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0]],
      dtype=int64)

In [16]:
y_test_2 = np.reshape(y_test,(y_test.shape[0], number_steps, number_edges))
y_test_2.shape

(20000, 4, 19)

In [17]:
X2[1,:]

array([20, 70, 90, 20, 60, 40, 90, 70, 10, 60, 60, 80, 10, 20, 60, 20, 70,
       40, 20], dtype=int64)

In [33]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,TimeDistributed,LSTM
# Neural network
model = Sequential()
model.add(LSTM(64, input_shape=(number_steps, number_edges), return_sequences=True))
model.add(LSTM(64, return_sequences=True))
model.add(LSTM(64, return_sequences=True))
model.add(TimeDistributed(Dense(number_edges, activation='sigmoid')))

In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 4, 64)             21504     
                                                                 
 lstm_3 (LSTM)               (None, 4, 64)             33024     
                                                                 
 lstm_4 (LSTM)               (None, 4, 64)             33024     
                                                                 
 time_distributed_1 (TimeDis  (None, 4, 19)            1235      
 tributed)                                                       
                                                                 
Total params: 88,787
Trainable params: 88,787
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss='BinaryCrossentropy', optimizer='adam')

In [21]:
model.fit(X_train, y_train_2, epochs=200, batch_size=128)

Epoch 1/200
1407/1407 [==============================] - 14s 8ms/step - loss: 0.3440
Epoch 2/200
1407/1407 [==============================] - 11s 8ms/step - loss: 0.2662
Epoch 3/200
1407/1407 [==============================] - 11s 8ms/step - loss: 0.2383
Epoch 4/200
1407/1407 [==============================] - 11s 8ms/step - loss: 0.2212
Epoch 5/200
1407/1407 [==============================] - 11s 8ms/step - loss: 0.2094
Epoch 6/200
1407/1407 [==============================] - 11s 8ms/step - loss: 0.2003
Epoch 7/200
1407/1407 [==============================] - 11s 8ms/step - loss: 0.1929
Epoch 8/200
1407/1407 [==============================] - 14s 10ms/step - loss: 0.1867
Epoch 9/200
1407/1407 [==============================] - 12s 8ms/step - loss: 0.1816
Epoch 10/200
1407/1407 [==============================] - 12s 8ms/step - loss: 0.1770
Epoch 11/200
1407/1407 [==============================] - 12s 8ms/step - loss: 0.1729
Epoch 12/200
1407/1407 [==============================] - 12s 

1407/1407 [==============================] - 12s 9ms/step - loss: 0.1054
Epoch 97/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1051
Epoch 98/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1050
Epoch 99/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1048
Epoch 100/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1045
Epoch 101/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1043
Epoch 102/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1040
Epoch 103/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1038
Epoch 104/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1036
Epoch 105/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1034
Epoch 106/200
1407/1407 [==============================] - 12s 9ms/step - loss: 0.1032
Epoch 107/200
1407/1407 [==============================] - 1

1407/1407 [==============================] - 15s 11ms/step - loss: 0.0913
Epoch 190/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0913
Epoch 191/200
1407/1407 [==============================] - 16s 11ms/step - loss: 0.0911
Epoch 192/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0912
Epoch 193/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0911
Epoch 194/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0909
Epoch 195/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0908
Epoch 196/200
1407/1407 [==============================] - 16s 11ms/step - loss: 0.0907
Epoch 197/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0906
Epoch 198/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0905
Epoch 199/200
1407/1407 [==============================] - 15s 11ms/step - loss: 0.0904
Epoch 200/200
1407/1407 [=====================

In [22]:
len(model.layers)

3

In [23]:
pred=model.predict(X_train)

5625/5625 [==============================] - 14s 2ms/step


In [24]:
pred.shape

(180000, 4, 19)

In [25]:
pred[0]

array([[5.2645497e-05, 9.9986243e-01, 1.5320248e-04, 1.8277693e-05,
        2.4568772e-05, 2.8807488e-05, 6.8137924e-06, 9.3070939e-06,
        1.0587283e-03, 6.5463985e-04, 9.9997467e-01, 4.1351534e-04,
        2.3004934e-03, 9.6390129e-04, 9.9964410e-01, 9.9205726e-01,
        9.8926151e-01, 1.7262881e-03, 1.4444669e-03],
       [1.2032042e-03, 9.7657174e-01, 7.5457253e-02, 1.2444195e-03,
        1.3854970e-03, 2.0886936e-04, 1.1475869e-03, 2.5710762e-03,
        5.5753347e-04, 1.8933954e-04, 9.5673883e-01, 1.4317164e-01,
        9.0285530e-03, 2.2124265e-01, 1.6678873e-01, 9.9711752e-01,
        9.9792886e-01, 9.8119479e-01, 7.1974733e-04],
       [4.5462375e-04, 7.1710980e-01, 5.2334154e-01, 1.3788745e-03,
        1.1477082e-03, 3.1208041e-05, 9.0129394e-04, 3.7742406e-03,
        5.3762265e-05, 2.8095106e-05, 3.7401792e-01, 7.1333605e-03,
        2.7647156e-02, 6.2521958e-01, 4.8529822e-02, 9.8998630e-01,
        9.9492586e-01, 9.5042586e-01, 1.1262394e-02],
       [7.0746434e-03,

In [26]:
y_train_2[0]

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0]],
      dtype=int64)

In [27]:
import copy
def cost_path(x,y):
    cost = 0
    path = []
    for i in range(number_edges):
        if y[i]==1:
            path.append(edges[i])
            cost+= x[i]
    if(len(path)!=0):
        path_2 = copy.deepcopy(path)
        path_nodes = [start_node]
        if(path[0][0]!=start_node):
            cost = 0
        else:
            path_nodes.append(path[0][1])
            del path_2[0]
            condition = True
            while(len(path_2)!=0 and condition):
                condition = False
                for i in range(len(path_2)):
                    if(path_nodes[-1] in path_2[i]):
                        path_2[i].remove(path_nodes[-1])
                        path_nodes.append(path_2[i][0])
                        path_2.pop(i)
                        condition = True
                        break
        if(path_nodes[-1]!=end_node or len(path_2)!=0):
            cost = 0
    else:
        cost = 0
    return cost

In [28]:
cost_path(X1[1],y_train[1])

100

In [29]:
accuracy = np.zeros(number_steps+1)
for i in range(pred.shape[0]):
    condition_1 = True
    for t in range(number_steps):
        output = copy.deepcopy(pred[i][t])
        condition_2 = True
        for j in range(len(output)):
            output[j] = round(output[j])
        if(cost_path(X1[i],output) != cost_path(X1[i],y_train_2[i][t])):
            condition_2 = False
            condition_1 = False
        if condition_2:
            accuracy[t] += 1
    if condition_1:
        accuracy[number_steps] += 1
accuracy = np.round(accuracy / pred.shape[0] * 100,2)
accuracy

array([90.53, 80.45, 72.38, 55.72, 40.67])

In [30]:
pred_test=model.predict(X_test)

625/625 [==============================] - 2s 3ms/step


In [31]:
accuracy_test = np.zeros(number_steps+1)
for i in range(pred_test.shape[0]):
    condition_1 = True
    for t in range(number_steps):
        output = copy.deepcopy(pred_test[i][t])
        condition_2 = True
        for j in range(len(output)):
            output[j] = round(output[j])
        if(cost_path(X1[i],output) != cost_path(X1[i],y_test_2[i][t])):
            condition_2 = False
            condition_1 = False
        if condition_2:
            accuracy_test[t] += 1
    if condition_1:
        accuracy_test[number_steps] += 1
accuracy_test = np.round(accuracy_test / pred_test.shape[0] * 100,2)
accuracy_test

array([90.3 , 78.  , 67.54, 49.27, 36.24])

In [32]:
model.summary()
print(accuracy)
print(accuracy_test)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 4, 64)             21504     
                                                                 
 lstm_1 (LSTM)               (None, 4, 64)             33024     
                                                                 
 time_distributed (TimeDistr  (None, 4, 19)            1235      
 ibuted)                                                         
                                                                 
Total params: 55,763
Trainable params: 55,763
Non-trainable params: 0
_________________________________________________________________
[90.53 80.45 72.38 55.72 40.67]
[90.3  78.   67.54 49.27 36.24]
