In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("../Data/data_12_12_yen.csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 6)  X(4, 5)  \
0       20       10       90       40       50       50       90       30   
1       10       10       60       30       40       70       50       70   
2       40       90       40       80       40       60       50       40   
3       30       20       10       20       20       90       80       60   
4       10       40       70       40       20       30       70       50   

   X(4, 6)  X(4, 7)  ...  Y4(1, 4)  Y4(2, 4)  Y4(2, 5)  Y4(3, 4)  Y4(3, 6)  \
0       70       90  ...         1         0         0         0         0   
1       70       90  ...         1         0         0         0         0   
2       50       50  ...         0         1         0         0         0   
3       30       50  ...         1         0         0         0         0   
4       80       70  ...         0         0         0         1         0   

   Y4(4, 5)  Y4(4, 6)  Y4(4, 7)  Y4(5, 7)  Y4(6, 7)  
0         1         0         0         0         0  
1         1         0         0         0         0  
2         1         0         0         0         0  
3         0         0         1         1         0  
4         1         0         0         0         0  

[5 rows x 60 columns]

In [2]:
X = dataset.iloc[:,:12].values
y = dataset.iloc[:,12:60].values

In [3]:
X.shape

(100000, 12)

In [4]:
y.shape

(100000, 48)

In [5]:
y[0].shape[0]

48

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [7]:
X[1,:]

array([-1.55013727, -1.55235664,  0.38954234, -0.76772508, -0.38633749,
        0.77444228,  0.00211055,  0.7803807 ,  0.77406685,  1.55269907,
       -1.55541596, -1.16284333])

In [8]:
y[1,:]

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [10]:
X_test[1,:]

array([-0.00156019, -1.55235664,  1.549539  , -1.54194197,  1.55447177,
        1.55144478, -1.15966128, -0.76800138,  0.38686499, -0.38409298,
       -1.16750846,  1.16059733])

In [11]:
y_test[1,:]

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0], dtype=int64)

In [12]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(100, input_dim=12, activation="relu"))
model.add(Dense(100, activation="relu"))
model.add(Dense(100, activation="relu"))
model.add(Dense(100, activation="relu"))
model.add(Dense(48, activation="sigmoid"))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
model.fit(X_train, y_train, epochs=200, batch_size=64)

Epoch 1/200
1407/1407 [==============================] - 3s 2ms/step - loss: 0.2760 - accuracy: 0.5001
Epoch 2/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.1827 - accuracy: 0.6369
Epoch 3/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.1496 - accuracy: 0.6525
Epoch 4/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.1295 - accuracy: 0.6367
Epoch 5/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.1169 - accuracy: 0.6399
Epoch 6/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.1082 - accuracy: 0.6404
Epoch 7/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.1010 - accuracy: 0.6493
Epoch 8/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0961 - accuracy: 0.6325
Epoch 9/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0908 - accuracy: 0.6160
Epoch 10/200
1407/1407 [==============================] - 2s 2ms/step - l

1407/1407 [==============================] - 2s 2ms/step - loss: 0.0318 - accuracy: 0.3067
Epoch 80/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0326 - accuracy: 0.2972
Epoch 81/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0320 - accuracy: 0.2879
Epoch 82/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0312 - accuracy: 0.2811
Epoch 83/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0315 - accuracy: 0.2829
Epoch 84/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0316 - accuracy: 0.2923
Epoch 85/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0313 - accuracy: 0.2917
Epoch 86/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0309 - accuracy: 0.2967
Epoch 87/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0310 - accuracy: 0.2881
Epoch 88/200
1407/1407 [==============================] - 2s 1ms/step - loss:

1407/1407 [==============================] - 2s 1ms/step - loss: 0.0247 - accuracy: 0.2569
Epoch 157/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0235 - accuracy: 0.2626
Epoch 158/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0244 - accuracy: 0.2644
Epoch 159/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0245 - accuracy: 0.2652
Epoch 160/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0241 - accuracy: 0.2797
Epoch 161/200
1407/1407 [==============================] - 2s 1ms/step - loss: 0.0237 - accuracy: 0.2711
Epoch 162/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0236 - accuracy: 0.2622
Epoch 163/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0245 - accuracy: 0.2632
Epoch 164/200
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0232 - accuracy: 0.2652
Epoch 165/200
1407/1407 [==============================] - 2s 2ms/ste

In [15]:
loss_and_metrics = model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 964us/step - loss: 0.0458 - accuracy: 0.2702


In [16]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

2813/2813 [==============================] - 3s 895us/step - loss: 0.0211 - accuracy: 0.2699


In [17]:
len(model.layers)

5

In [18]:
X_train[0]

array([-1.55013727,  0.77396831, -1.15711987,  0.39360025,  1.16630992,
       -0.39106147, -0.77240401,  0.39328518,  0.38686499, -1.54616821,
        0.77202901, -0.77560322])

In [19]:
X_test[2].reshape(1,len(X_test[2]))

array([[-0.38870446, -1.55235664, -0.38378876,  1.55492558, -1.16266119,
        -1.55656523, -1.54691856, -0.38090586,  0.38686499,  0.77798225,
         1.15993651, -1.16284333]])

In [20]:
pr=model.predict(X_test[1:2,:])

In [21]:
pr

array([[9.99998927e-01, 9.71750893e-08, 1.22828608e-15, 9.99998927e-01,
        6.74291467e-09, 4.15555235e-09, 1.09781828e-11, 1.00000000e+00,
        3.76446548e-14, 1.23795147e-17, 4.64015937e-10, 3.38957716e-11,
        2.26169825e-03, 9.97106552e-01, 8.70296359e-02, 1.56891983e-05,
        4.92560863e-02, 9.29367542e-03, 9.80995893e-01, 4.72643137e-01,
        6.16997480e-04, 7.48109378e-05, 2.58463621e-03, 3.69081497e-02,
        2.23750770e-01, 8.70749354e-03, 1.68637037e-02, 4.64074016e-02,
        1.25408173e-04, 1.69249518e-06, 2.69451737e-03, 9.51798558e-01,
        1.04013085e-03, 1.34639740e-02, 1.10693514e-01, 4.09293175e-03,
        7.36230254e-01, 2.24955887e-01, 8.90721679e-02, 5.83939552e-01,
        3.27881962e-01, 2.75347829e-02, 3.07660878e-01, 1.92712456e-01,
        9.56735909e-02, 8.65709424e-01, 4.27281082e-01, 9.90217924e-03]],
      dtype=float32)

In [22]:
y_test[1:2,:]

array([[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0]], dtype=int64)

In [23]:
pred=model.predict(X_train)

In [24]:
pred.shape[0]

90000

In [25]:
pred[0]

array([7.8823711e-11, 0.0000000e+00, 1.0000000e+00, 3.5343978e-37,
       4.0818657e-17, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 3.5526181e-30, 0.0000000e+00,
       1.0000000e+00, 0.0000000e+00, 1.1055895e-10, 7.8523322e-14,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 8.0908893e-18,
       0.0000000e+00, 2.6043915e-15, 1.6492433e-15, 0.0000000e+00,
       3.5972920e-16, 0.0000000e+00, 1.0000000e+00, 2.1313370e-20,
       1.5016875e-15, 2.2939435e-38, 5.1733312e-37, 2.5355131e-17,
       2.4858548e-25, 1.0000000e+00, 1.0000000e+00, 7.8889532e-31,
       1.0000000e+00, 3.3979933e-14, 1.0520653e-10, 1.0000000e+00,
       5.7968619e-11, 5.7228688e-12, 3.7140587e-13, 1.0000000e+00,
       2.4488957e-12, 6.1932637e-10, 6.7764754e-09, 1.5030029e-11],
      dtype=float32)

In [26]:
y_train[0]

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0], dtype=int64)

In [27]:
accuracy = 0
for i in range(pred.shape[0]):
    output = pred[i]
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y_train[i][j]):
            condition = False
            break
    if condition:
        accuracy += 1
accuracy / pred.shape[0] * 100

85.74444444444444

In [28]:
pred_test=model.predict(X_test)

In [29]:
accuracy_test = 0
for i in range(pred_test.shape[0]):
    output = pred_test[i]
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y_test[i][j]):
            condition = False
            break
    if condition:
        accuracy_test += 1
accuracy_test / pred_test.shape[0] * 100

81.37