In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("../Data/data_18_yen.csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 7)  X(4, 5)  \
0       30       70       70       10       90       10       60       60   
1       10       80       30       10       80       30       20       50   
2       90       40       30       10       70       60       30       10   
3       30       40       90       20       50       20       10       50   
4       20       60       20       40       10       50       60       50   

   X(4, 6)  X(4, 7)  ...  Y4(5, 9)  Y4(6, 7)  Y4(6, 8)  Y4(7, 8)  Y4(7, 9)  \
0       90       30  ...         0         0         0         0         1   
1       30       70  ...         0         0         1         0         0   
2       40       50  ...         1         0         0         0         0   
3       10       80  ...         1         0         0         0         0   
4       20       80  ...         0         0         1         0         0   

   Y4(8, 9)      Y1      Y2      Y3      Y4  
0         0  147714   33026  153602   69890  
1         1  147977  153602  147982   33289  
2         0   33824   33857   70688   57376  
3         0   67586  139296  153602  148512  
4         1  139296   33824   57376   33289  

[5 rows x 94 columns]

In [2]:
# t = 18
# dataset["Y1"] = (pow(2,t-1)*dataset.iloc[:,t]+pow(2,t-2)*dataset.iloc[:,t+1]+pow(2,t-3)*dataset.iloc[:,t+2]
# +pow(2,t-4)*dataset.iloc[:,t+3]+pow(2,t-5)*dataset.iloc[:,t+4]+pow(2,t-6)*dataset.iloc[:,t+5]
# +pow(2,t-7)*dataset.iloc[:,t+6]+pow(2,t-8)*dataset.iloc[:,t+7]+pow(2,t-9)*dataset.iloc[:,t+8]
# +pow(2,t-10)*dataset.iloc[:,t+9]+pow(2,t-11)*dataset.iloc[:,t+10]+pow(2,t-12)*dataset.iloc[:,t+11]
# +pow(2,t-13)*dataset.iloc[:,t+12]+pow(2,t-14)*dataset.iloc[:,t+13]+pow(2,t-15)*dataset.iloc[:,t+14]
# +pow(2,t-16)*dataset.iloc[:,t+15]+pow(2,t-17)*dataset.iloc[:,t+16]+pow(2,t-18)*dataset.iloc[:,t+17])
# dataset["Y1"]

In [3]:
# t = 36
# t1 = 18
# dataset["Y2"] = (pow(2,t1-1)*dataset.iloc[:,t]+pow(2,t1-2)*dataset.iloc[:,t+1]+pow(2,t1-3)*dataset.iloc[:,t+2]
# +pow(2,t1-4)*dataset.iloc[:,t+3]+pow(2,t1-5)*dataset.iloc[:,t+4]+pow(2,t1-6)*dataset.iloc[:,t+5]
# +pow(2,t1-7)*dataset.iloc[:,t+6]+pow(2,t1-8)*dataset.iloc[:,t+7]+pow(2,t1-9)*dataset.iloc[:,t+8]
# +pow(2,t1-10)*dataset.iloc[:,t+9]+pow(2,t1-11)*dataset.iloc[:,t+10]+pow(2,t1-12)*dataset.iloc[:,t+11]
# +pow(2,t1-13)*dataset.iloc[:,t+12]+pow(2,t1-14)*dataset.iloc[:,t+13]+pow(2,t1-15)*dataset.iloc[:,t+14]
# +pow(2,t1-16)*dataset.iloc[:,t+15]+pow(2,t1-17)*dataset.iloc[:,t+16]+pow(2,t1-18)*dataset.iloc[:,t+17])
# dataset["Y2"]

In [4]:
# t = 54
# t1 = 18
# dataset["Y3"] = (pow(2,t1-1)*dataset.iloc[:,t]+pow(2,t1-2)*dataset.iloc[:,t+1]+pow(2,t1-3)*dataset.iloc[:,t+2]
# +pow(2,t1-4)*dataset.iloc[:,t+3]+pow(2,t1-5)*dataset.iloc[:,t+4]+pow(2,t1-6)*dataset.iloc[:,t+5]
# +pow(2,t1-7)*dataset.iloc[:,t+6]+pow(2,t1-8)*dataset.iloc[:,t+7]+pow(2,t1-9)*dataset.iloc[:,t+8]
# +pow(2,t1-10)*dataset.iloc[:,t+9]+pow(2,t1-11)*dataset.iloc[:,t+10]+pow(2,t1-12)*dataset.iloc[:,t+11]
# +pow(2,t1-13)*dataset.iloc[:,t+12]+pow(2,t1-14)*dataset.iloc[:,t+13]+pow(2,t1-15)*dataset.iloc[:,t+14]
# +pow(2,t1-16)*dataset.iloc[:,t+15]+pow(2,t1-17)*dataset.iloc[:,t+16]+pow(2,t1-18)*dataset.iloc[:,t+17])
# dataset["Y3"]

In [5]:
# t = 72
# t1 = 18
# dataset["Y4"] = (pow(2,t1-1)*dataset.iloc[:,t]+pow(2,t1-2)*dataset.iloc[:,t+1]+pow(2,t1-3)*dataset.iloc[:,t+2]
# +pow(2,t1-4)*dataset.iloc[:,t+3]+pow(2,t1-5)*dataset.iloc[:,t+4]+pow(2,t1-6)*dataset.iloc[:,t+5]
# +pow(2,t1-7)*dataset.iloc[:,t+6]+pow(2,t1-8)*dataset.iloc[:,t+7]+pow(2,t1-9)*dataset.iloc[:,t+8]
# +pow(2,t1-10)*dataset.iloc[:,t+9]+pow(2,t1-11)*dataset.iloc[:,t+10]+pow(2,t1-12)*dataset.iloc[:,t+11]
# +pow(2,t1-13)*dataset.iloc[:,t+12]+pow(2,t1-14)*dataset.iloc[:,t+13]+pow(2,t1-15)*dataset.iloc[:,t+14]
# +pow(2,t1-16)*dataset.iloc[:,t+15]+pow(2,t1-17)*dataset.iloc[:,t+16]+pow(2,t1-18)*dataset.iloc[:,t+17])
# dataset["Y4"]

In [6]:
X = dataset.iloc[:,:18].values
y = dataset.iloc[:,18:90].values

In [7]:
X.shape

(200000, 18)

In [8]:
y.shape

(200000, 72)

In [9]:
y[0].shape[0]

72

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [11]:
X[1,:]

array([-1.54856409e+00,  1.16335885e+00, -7.71235704e-01, -1.55127599e+00,
        1.15961027e+00, -7.75380349e-01, -1.16593451e+00,  7.71184836e-04,
       -7.72775321e-01,  7.75331179e-01,  1.54601773e+00, -7.75959711e-01,
        1.16135131e+00, -3.85585178e-01, -1.54919761e+00, -1.54849659e+00,
       -7.72386858e-01, -3.87602375e-01])

In [12]:
y[1,:]

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1], dtype=int64)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [14]:
X_test[1,:]

array([-0.38667481, -0.77307134, -1.5449861 , -0.3873054 , -0.00358069,
       -1.16294844, -1.55352897, -0.77428895, -1.16057554,  1.16260369,
       -0.00386696, -1.55119651, -0.77507332,  0.77585677,  1.16398057,
       -0.38561531, -1.1595055 , -0.38760238])

In [15]:
y_test[1,:]

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1], dtype=int64)

In [16]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(128, input_dim=18, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(256, activation="relu"))
model.add(Dense(1024, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(256, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(72, activation="sigmoid"))

In [17]:
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])

In [18]:
model.fit(X_train, y_train, epochs=100, batch_size=64)

Epoch 1/100
2813/2813 [==============================] - 19s 7ms/step - loss: 0.0978 - accuracy: 0.3676
Epoch 2/100
2813/2813 [==============================] - 18s 7ms/step - loss: 0.0845 - accuracy: 0.3430
Epoch 3/100
2813/2813 [==============================] - 19s 7ms/step - loss: 0.0796 - accuracy: 0.3257
Epoch 4/100
2813/2813 [==============================] - 19s 7ms/step - loss: 0.0766 - accuracy: 0.3279
Epoch 5/100
2813/2813 [==============================] - 18s 7ms/step - loss: 0.0743 - accuracy: 0.3405
Epoch 6/100
2813/2813 [==============================] - 18s 7ms/step - loss: 0.0725 - accuracy: 0.3423
Epoch 7/100
2813/2813 [==============================] - 19s 7ms/step - loss: 0.0709 - accuracy: 0.3429
Epoch 8/100
2813/2813 [==============================] - 17s 6ms/step - loss: 0.0696 - accuracy: 0.3245
Epoch 9/100
2813/2813 [==============================] - 17s 6ms/step - loss: 0.0684 - accuracy: 0.3301
Epoch 10/100
2813/2813 [==============================] - 19s 7m

2813/2813 [==============================] - 18s 7ms/step - loss: 0.0521 - accuracy: 0.6617
Epoch 79/100
2813/2813 [==============================] - 18s 6ms/step - loss: 0.0519 - accuracy: 0.6691
Epoch 80/100
2813/2813 [==============================] - 18s 6ms/step - loss: 0.0520 - accuracy: 0.6694
Epoch 81/100
2813/2813 [==============================] - 18s 7ms/step - loss: 0.0520 - accuracy: 0.6572
Epoch 82/100
2813/2813 [==============================] - 18s 7ms/step - loss: 0.0518 - accuracy: 0.6642
Epoch 83/100
2813/2813 [==============================] - 18s 6ms/step - loss: 0.0517 - accuracy: 0.6674
Epoch 84/100
2813/2813 [==============================] - 18s 6ms/step - loss: 0.0517 - accuracy: 0.6711
Epoch 85/100
2813/2813 [==============================] - 18s 7ms/step - loss: 0.0516 - accuracy: 0.6796
Epoch 86/100
2813/2813 [==============================] - 18s 6ms/step - loss: 0.0516 - accuracy: 0.6790
Epoch 87/100
2813/2813 [==============================] - 18s 7ms/st

In [19]:
loss_and_metrics = model.evaluate(X_test, y_test)

625/625 [==============================] - 1s 2ms/step - loss: 0.0489 - accuracy: 0.7462


In [20]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

5625/5625 [==============================] - 10s 2ms/step - loss: 0.0438 - accuracy: 0.7467


In [21]:
len(model.layers)

8

In [22]:
X_train[0]

array([-7.73971238e-01,  1.16335885e+00,  3.89389885e-01,  6.84802700e-04,
        1.15961027e+00,  1.55002819e+00, -3.15114293e-03,  1.55089146e+00,
       -1.16057554e+00,  3.88058671e-01,  1.54601773e+00, -7.75959711e-01,
       -1.16235825e+00,  1.55015141e+00,  1.16398057e+00,  1.16489306e+00,
        1.55032500e+00, -3.13703824e-04])

In [23]:
X_test[2].reshape(1,len(X_test[2]))

array([[-1.16126766, -0.77307134,  0.38938989,  1.1646554 , -0.00358069,
        -0.77538035, -1.16593451,  0.77583132, -0.77277532,  0.77533118,
         0.38360421,  1.1621323 , -0.3877884 , -0.77273249,  0.77638369,
         0.00201178,  0.38896907,  1.54884098]])

In [24]:
pr=model.predict(X_test[1:2,:])

In [25]:
pr

array([[0.00000000e+00, 9.99711156e-01, 7.48008490e-04, 0.00000000e+00,
        0.00000000e+00, 1.72009040e-05, 9.93503213e-01, 7.05635548e-03,
        0.00000000e+00, 3.57663688e-20, 0.00000000e+00, 4.34191627e-10,
        2.50524282e-03, 0.00000000e+00, 0.00000000e+00, 6.39520574e-23,
        9.90082860e-01, 2.24783912e-18, 6.12636696e-17, 4.86777037e-01,
        8.58916044e-01, 3.17955611e-31, 6.72378752e-14, 8.39084148e-01,
        8.92377019e-01, 1.61233634e-01, 1.17564165e-33, 9.41847915e-08,
        3.37563518e-37, 1.45885348e-03, 5.25960922e-02, 1.14680393e-21,
        3.56331345e-30, 7.39822070e-08, 9.61729884e-01, 1.10120745e-05,
        7.83743872e-06, 4.26428020e-02, 9.69470739e-01, 1.41847236e-08,
        4.63122979e-06, 6.46185994e-01, 4.42971230e-01, 3.52908432e-01,
        1.29273906e-06, 1.61725879e-02, 1.54013685e-06, 6.36595488e-03,
        4.08874840e-01, 1.82796302e-05, 3.99373675e-06, 1.79802179e-02,
        6.12428546e-01, 1.13237798e-02, 1.88276172e-03, 3.924971

In [26]:
y_test[1:2,:]

array([[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1]], dtype=int64)

In [27]:
pred=model.predict(X_train)

In [28]:
pred.shape[0]

180000

In [29]:
pred[0]

array([1.0000000e+00, 0.0000000e+00, 6.3312077e-12, 8.4273812e-28,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5193414e-09,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.6746520e-35,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.1201331e-18, 6.4969648e-28, 7.0022511e-06, 3.8049057e-17,
       9.9999571e-01, 2.3245127e-06, 5.1253996e-06, 0.0000000e+00,
       2.7333355e-17, 9.9998957e-01, 2.3177073e-18, 5.1957585e-22,
       3.3926093e-23, 4.8740494e-06, 9.9990082e-01, 2.5266007e-25,
       2.3289145e-29, 5.9832650e-24, 1.8340439e-08, 5.1541359e-05,
       9.8524845e-01, 3.0242888e-06, 1.8646866e-02, 9.3005991e-01,
       1.4574242e-01, 5.8074942e-12, 9.6438418e-07, 8.6226356e-01,
       5.7604909e-04, 2.0131713e-05, 5.1343441e-04, 1.4178243e-01,
       9.3913120e-01, 4.8765811e-05, 3.3272492e-05, 3.0115247e-04,
       2.3838878e-04, 8.3205312e-02, 8.2299972e-01, 1.3390481e-03,
       3.2953545e-01, 1.6385874e-01, 8.1371665e-01, 4.4669778e

In [30]:
t = pred[0].copy()
t[0] = 0
t

array([0.0000000e+00, 0.0000000e+00, 6.3312077e-12, 8.4273812e-28,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5193414e-09,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.6746520e-35,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.1201331e-18, 6.4969648e-28, 7.0022511e-06, 3.8049057e-17,
       9.9999571e-01, 2.3245127e-06, 5.1253996e-06, 0.0000000e+00,
       2.7333355e-17, 9.9998957e-01, 2.3177073e-18, 5.1957585e-22,
       3.3926093e-23, 4.8740494e-06, 9.9990082e-01, 2.5266007e-25,
       2.3289145e-29, 5.9832650e-24, 1.8340439e-08, 5.1541359e-05,
       9.8524845e-01, 3.0242888e-06, 1.8646866e-02, 9.3005991e-01,
       1.4574242e-01, 5.8074942e-12, 9.6438418e-07, 8.6226356e-01,
       5.7604909e-04, 2.0131713e-05, 5.1343441e-04, 1.4178243e-01,
       9.3913120e-01, 4.8765811e-05, 3.3272492e-05, 3.0115247e-04,
       2.3838878e-04, 8.3205312e-02, 8.2299972e-01, 1.3390481e-03,
       3.2953545e-01, 1.6385874e-01, 8.1371665e-01, 4.4669778e

In [31]:
pred[0]

array([1.0000000e+00, 0.0000000e+00, 6.3312077e-12, 8.4273812e-28,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5193414e-09,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.6746520e-35,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.1201331e-18, 6.4969648e-28, 7.0022511e-06, 3.8049057e-17,
       9.9999571e-01, 2.3245127e-06, 5.1253996e-06, 0.0000000e+00,
       2.7333355e-17, 9.9998957e-01, 2.3177073e-18, 5.1957585e-22,
       3.3926093e-23, 4.8740494e-06, 9.9990082e-01, 2.5266007e-25,
       2.3289145e-29, 5.9832650e-24, 1.8340439e-08, 5.1541359e-05,
       9.8524845e-01, 3.0242888e-06, 1.8646866e-02, 9.3005991e-01,
       1.4574242e-01, 5.8074942e-12, 9.6438418e-07, 8.6226356e-01,
       5.7604909e-04, 2.0131713e-05, 5.1343441e-04, 1.4178243e-01,
       9.3913120e-01, 4.8765811e-05, 3.3272492e-05, 3.0115247e-04,
       2.3838878e-04, 8.3205312e-02, 8.2299972e-01, 1.3390481e-03,
       3.2953545e-01, 1.6385874e-01, 8.1371665e-01, 4.4669778e

In [32]:
y_train[0]

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1], dtype=int64)

In [33]:
accuracy = 0
for i in range(pred.shape[0]):
    output = pred[i].copy()
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y_train[i][j]):
            condition = False
            break
    if condition:
        accuracy += 1
accuracy / pred.shape[0] * 100

28.363333333333333

In [34]:
pred_test=model.predict(X_test)

In [35]:
accuracy_test = 0
for i in range(pred_test.shape[0]):
    output = pred_test[i].copy()
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y_test[i][j]):
            condition = False
            break
    if condition:
        accuracy_test += 1
accuracy_test / pred_test.shape[0] * 100

25.195