In [1]:
import numpy as np
import pandas as pd
#dataset import
dataset = pd.read_csv("../Data/data_8_8_yen.csv") #You need to change #directory accordingly
dataset.head()

X(1, 2)  X(1, 3)  X(1, 4)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 5)  X(4, 5)  \
0       10       50       10       30       10       80       10       30   
1       90       50       20       80       80       50       80       60   
2       70       90       40       40       30       90       50       70   
3       60       20       80       40       10       30       40       30   
4       20       20       40       50       50       60       50       40   

   Y1(1, 2)  Y1(1, 3)  ...  Y2(3, 5)  Y2(4, 5)  Y3(1, 2)  Y3(1, 3)  Y3(1, 4)  \
0         1         0  ...         0         1         0         1         0   
1         0         0  ...         1         0         1         0         0   
2         1         0  ...         0         1         0         1         0   
3         0         1  ...         0         0         0         0         1   
4         1         0  ...         1         0         0         0         1   

   Y3(2, 4)  Y3(2, 5)  Y3(3, 4)  Y3(3, 5)  Y3(4, 5)  
0         0         0         0         1         0  
1         0         1         0         0         0  
2         0         0         0         1         0  
3         0         0         0         0         1  
4         0         0         0         0         1  

[5 rows x 32 columns]

In [2]:
X = dataset.iloc[:,:8].values
y = dataset.iloc[:,8:32].values

In [3]:
X.shape

(10000, 8)

In [4]:
y.shape

(10000, 24)

In [5]:
y[0].shape[0]

24

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [7]:
X[1,:]

array([ 1.55208494,  0.00845373, -1.12581085,  1.1564365 ,  1.15423307,
        0.01570705,  1.16769522,  0.39676295])

In [8]:
y[1,:]

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [10]:
X_test[1,:]

array([-0.77023667, -0.37933184, -0.74169305, -1.5647735 ,  0.38335678,
        0.79136361,  0.78002707, -1.15188246])

In [11]:
y_test[1,:]

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0], dtype=int64)

In [12]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(8, input_dim=8, activation="relu"))
model.add(Dense(100, activation="relu"))
model.add(Dense(100, activation="relu"))
model.add(Dense(24, activation="sigmoid"))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
model.fit(X_train, y_train, epochs=200, batch_size=16)

Epoch 1/200
563/563 [==============================] - 1s 1ms/step - loss: 0.3714 - accuracy: 0.2524
Epoch 2/200
563/563 [==============================] - 1s 1ms/step - loss: 0.2446 - accuracy: 0.4404
Epoch 3/200
563/563 [==============================] - 1s 1ms/step - loss: 0.2193 - accuracy: 0.4569
Epoch 4/200
563/563 [==============================] - 1s 1ms/step - loss: 0.2048 - accuracy: 0.4363
Epoch 5/200
563/563 [==============================] - 1s 1ms/step - loss: 0.1926 - accuracy: 0.4074
Epoch 6/200
563/563 [==============================] - 1s 1ms/step - loss: 0.1803 - accuracy: 0.4102
Epoch 7/200
563/563 [==============================] - 1s 1ms/step - loss: 0.1703 - accuracy: 0.4061
Epoch 8/200
563/563 [==============================] - 1s 1ms/step - loss: 0.1600 - accuracy: 0.4202
Epoch 9/200
563/563 [==============================] - 1s 1ms/step - loss: 0.1499 - accuracy: 0.4052
Epoch 10/200
563/563 [==============================] - 1s 1ms/step - loss: 0.1401 - accura

563/563 [==============================] - 1s 896us/step - loss: 0.0171 - accuracy: 0.4553
Epoch 161/200
563/563 [==============================] - 1s 912us/step - loss: 0.0115 - accuracy: 0.4588
Epoch 162/200
563/563 [==============================] - 1s 1ms/step - loss: 0.0124 - accuracy: 0.4601
Epoch 163/200
563/563 [==============================] - 1s 2ms/step - loss: 0.0127 - accuracy: 0.4527
Epoch 164/200
563/563 [==============================] - 1s 2ms/step - loss: 0.0124 - accuracy: 0.4558
Epoch 165/200
563/563 [==============================] - 1s 901us/step - loss: 0.0105 - accuracy: 0.4550
Epoch 166/200
563/563 [==============================] - 1s 900us/step - loss: 0.0143 - accuracy: 0.4508
Epoch 167/200
563/563 [==============================] - 1s 902us/step - loss: 0.0123 - accuracy: 0.4499
Epoch 168/200
563/563 [==============================] - 1s 902us/step - loss: 0.0092 - accuracy: 0.4571
Epoch 169/200
563/563 [==============================] - 1s 895us/step - lo

In [15]:
loss_and_metrics = model.evaluate(X_test, y_test)

32/32 [==============================] - 0s 2ms/step - loss: 0.0302 - accuracy: 0.4370


In [16]:
loss_and_metrics_2 = model.evaluate(X_train, y_train)

282/282 [==============================] - 0s 807us/step - loss: 0.0087 - accuracy: 0.4394


In [17]:
len(model.layers)

4

In [18]:
X_train[0]

array([-0.38318306,  1.17181041,  0.02654254, -1.5647735 ,  1.53967122,
       -0.75994952,  0.78002707, -0.76472111])

In [19]:
X_test[2].reshape(1,len(X_test[2]))

array([[ 0.77797774, -0.7671174 ,  0.41066034, -0.78728493, -1.54383395,
        -0.37212124, -0.38297736,  1.55824701]])

In [20]:
pr=model.predict(X_test[1:2,:])

In [21]:
pr

array([[1.9063653e-12, 2.5564140e-24, 1.0000000e+00, 4.8224882e-11,
        0.0000000e+00, 2.5222413e-15, 1.8514984e-34, 1.0000000e+00,
        1.0000000e+00, 7.3827202e-29, 1.5794985e-08, 1.0000000e+00,
        2.5023893e-26, 6.1326446e-36, 1.9185103e-25, 1.0000000e+00,
        3.7786212e-26, 1.0000000e+00, 1.6533386e-29, 7.4619993e-29,
        0.0000000e+00, 4.8377850e-17, 1.0000000e+00, 1.2606470e-14]],
      dtype=float32)

In [22]:
y_test[1:2,:]

array([[0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 0]], dtype=int64)

In [23]:
pred=model.predict(X_train)

In [24]:
pred.shape[0]

9000

In [25]:
pred[0]

array([8.60929489e-04, 9.18903929e-12, 9.92746651e-01, 9.74732637e-03,
       0.00000000e+00, 1.96779024e-06, 1.11952966e-35, 1.00000000e+00,
       9.36893106e-01, 4.95475080e-20, 7.44694471e-03, 9.82033014e-01,
       0.00000000e+00, 6.12254071e-23, 1.42810392e-27, 1.00000000e+00,
       7.22534565e-25, 1.00000000e+00, 5.93989216e-18, 1.21875168e-21,
       0.00000000e+00, 9.98530030e-01, 3.33765149e-03, 9.25188899e-01],
      dtype=float32)

In [26]:
y_train[0]

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1], dtype=int64)

In [27]:
accuracy = 0
for i in range(pred.shape[0]):
    output = pred[i]
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y_train[i][j]):
            condition = False
            break
    if condition:
        accuracy += 1
accuracy / pred.shape[0] * 100

96.73333333333333

In [28]:
pred_test=model.predict(X_test)

In [29]:
accuracy_test = 0
for i in range(pred_test.shape[0]):
    output = pred_test[i]
    condition = True
    for j in range(len(output)):
        output[j] = round(output[j])
    for j in range(len(output)):
        if(output[j]!=y_test[i][j]):
            condition = False
            break
    if condition:
        accuracy_test += 1
accuracy_test / pred_test.shape[0] * 100

92.5