In [1]:
import numpy as np
import pandas as pd
#dataset import
df = pd.read_csv("../Data/data_8_nodes_yen.csv") #You need to change #directory accordingly
df.head()

X(1, 2)  X(1, 3)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 7)  X(4, 6)  X(5, 6)  \
0       10       40       30       50       30       20       20       10   
1       90       50       50       30       30       80       80       30   
2       10       60       80       50       40       50       30       90   
3       80       20       40       60       50       80       90       60   
4       20       70       50       40       20       70       80       80   

   X(5, 8)  X(6, 7)  ...  Y4(1, 3)  Y4(2, 4)  Y4(2, 5)  Y4(3, 4)  Y4(3, 7)  \
0       90       70  ...         0         1         0         0         0   
1       30       80  ...         1         0         0         1         0   
2       80       30  ...         1         0         0         1         0   
3       80       80  ...         1         0         0         1         0   
4       10       10  ...         0         1         0         0         0   

   Y4(4, 6)  Y4(5, 6)  Y4(5, 8)  Y4(6, 7)  Y4(7, 8)  
0         1         0         0         1         1  
1         1         1         1         0         0  
2         1         0         0         1         1  
3         1         1         1         0         0  
4         1         1         1         0         0  

[5 rows x 55 columns]

In [2]:
edges = [[1, 2], [1, 3], [2, 4], [2, 5], [3, 4], [3, 7], [4, 6], [5, 6], [5, 8], [6, 7], [7, 8]]

In [3]:
number_edges = 11
number_steps = 4
start_node = 1
end_node = 8

In [4]:
X = df.iloc[:,:number_edges].values
y = df.iloc[:,number_edges:].values

In [5]:
X.shape

(100000, 11)

In [6]:
y.shape

(100000, 44)

In [7]:
from sklearn.model_selection import train_test_split
X1,X2,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [8]:
X2[1]

array([20, 70, 20, 90, 20, 30, 50, 70, 50, 40, 10], dtype=int64)

In [9]:
y_test[1]

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
      dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X1)
X_test= sc.fit_transform(X2)

In [11]:
X_train = np.repeat(X_train[:, np.newaxis, : ], number_steps, axis=1)
X_train.shape

(90000, 4, 11)

In [12]:
X_test = np.repeat(X_test[:, np.newaxis, : ], number_steps, axis=1)
X_test.shape

(10000, 4, 11)

In [13]:
y_train[0]

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0],
      dtype=int64)

In [14]:
y_train_2 = np.reshape(y_train,(y_train.shape[0], number_steps, number_edges))
y_train_2.shape

(90000, 4, 11)

In [15]:
y_train_2[0]

array([[1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [16]:
y_test_2 = np.reshape(y_test,(y_test.shape[0], number_steps, number_edges))
y_test_2.shape

(10000, 4, 11)

In [17]:
X2[1,:]

array([20, 70, 20, 90, 20, 30, 50, 70, 50, 40, 10], dtype=int64)

In [18]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout,TimeDistributed,LSTM
# Neural network
model = Sequential()
model.add(LSTM(32, input_shape=(number_steps, number_edges), 
                    return_sequences=True))
model.add(LSTM(32, return_sequences=True))
model.add(TimeDistributed(Dense(number_edges, activation='sigmoid')))

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 4, 32)             5632      
                                                                 
 lstm_1 (LSTM)               (None, 4, 32)             8320      
                                                                 
 time_distributed (TimeDistr  (None, 4, 11)            363       
 ibuted)                                                         
                                                                 
Total params: 14,315
Trainable params: 14,315
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss='BinaryCrossentropy', optimizer='adam')

In [21]:
model.fit(X_train, y_train_2, epochs=100, batch_size=64)

Epoch 1/100
1407/1407 [==============================] - 10s 5ms/step - loss: 0.4209
Epoch 2/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.2137
Epoch 3/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.1586
Epoch 4/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.1301
Epoch 5/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.1123
Epoch 6/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.1000
Epoch 7/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0908
Epoch 8/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0838
Epoch 9/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0783
Epoch 10/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0735
Epoch 11/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0698
Epoch 12/100
1407/1407 [==============================] - 6s 4ms/step - l

1407/1407 [==============================] - 6s 4ms/step - loss: 0.0212
Epoch 98/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0214
Epoch 99/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0210
Epoch 100/100
1407/1407 [==============================] - 6s 4ms/step - loss: 0.0203


In [22]:
len(model.layers)

3

In [23]:
pred=model.predict(X_train)

2813/2813 [==============================] - 6s 2ms/step


In [24]:
pred.shape

(90000, 4, 11)

In [25]:
pred[0]

array([[1.00000000e+00, 4.72483812e-08, 7.04259890e-07, 9.99998629e-01,
        2.62577888e-08, 1.34464808e-05, 3.79182495e-07, 6.77132775e-05,
        9.99999642e-01, 3.07901246e-07, 3.85556177e-07],
       [3.37459454e-07, 9.99999642e-01, 7.11686766e-07, 1.00906846e-07,
        2.65782027e-08, 9.99996483e-01, 1.22328697e-06, 3.55765586e-08,
        5.02607307e-08, 2.55671875e-06, 1.00000000e+00],
       [9.99999762e-01, 2.50437779e-07, 9.99995947e-01, 2.62132608e-06,
        1.40070897e-05, 2.00190523e-04, 9.99972522e-01, 3.20517825e-06,
        3.99332180e-07, 9.99991477e-01, 9.99999583e-01],
       [2.04057767e-04, 9.99796033e-01, 9.99146342e-01, 9.98162448e-01,
        9.98092294e-01, 4.84714838e-04, 5.67043247e-03, 1.62542518e-03,
        9.99752104e-01, 2.23621819e-03, 2.47913413e-04]], dtype=float32)

In [26]:
y_train_2[0]

array([[1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [27]:
import copy
def cost_path(x,y):
    cost = 0
    path = []
    for i in range(number_edges):
        if y[i]==1:
            path.append(edges[i])
            cost+= x[i]
    if(len(path)!=0):
        path_2 = copy.deepcopy(path)
        path_nodes = [start_node]
        if(path[0][0]!=start_node):
            cost = 0
        else:
            path_nodes.append(path[0][1])
            del path_2[0]
            condition = True
            while(len(path_2)!=0 and condition):
                condition = False
                for i in range(len(path_2)):
                    if(path_nodes[-1] in path_2[i]):
                        path_2[i].remove(path_nodes[-1])
                        path_nodes.append(path_2[i][0])
                        path_2.pop(i)
                        condition = True
                        break
        if(path_nodes[-1]!=end_node or len(path_2)!=0):
            cost = 0
    else:
        cost = 0
    return cost

In [28]:
cost_path(X1[1],y_train[1])

80

In [29]:
accuracy = np.zeros(number_steps+1)
for i in range(pred.shape[0]):
    condition_1 = True
    for t in range(number_steps):
        output = copy.deepcopy(pred[i][t])
        condition_2 = True
        for j in range(len(output)):
            output[j] = round(output[j])
        if(cost_path(X1[i],output) != cost_path(X1[i],y_train_2[i][t])):
            condition_2 = False
            condition_1 = False
        if condition_2:
            accuracy[t] += 1
    if condition_1:
        accuracy[number_steps] += 1
accuracy = np.round(accuracy / pred.shape[0] * 100,2)
accuracy

array([98.63, 97.85, 97.56, 95.25, 91.61])

In [30]:
pred_test=model.predict(X_test)

313/313 [==============================] - 1s 2ms/step


In [31]:
accuracy_test = np.zeros(number_steps+1)
for i in range(pred_test.shape[0]):
    condition_1 = True
    for t in range(number_steps):
        output = copy.deepcopy(pred_test[i][t])
        condition_2 = True
        for j in range(len(output)):
            output[j] = round(output[j])
        if(cost_path(X1[i],output) != cost_path(X1[i],y_test_2[i][t])):
            condition_2 = False
            condition_1 = False
        if condition_2:
            accuracy_test[t] += 1
    if condition_1:
        accuracy_test[number_steps] += 1
accuracy_test = np.round(accuracy_test / pred_test.shape[0] * 100,2)
accuracy_test

array([98.45, 96.98, 96.37, 93.  , 88.82])

In [32]:
model.summary()
print(accuracy)
print(accuracy_test)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 4, 32)             5632      
                                                                 
 lstm_1 (LSTM)               (None, 4, 32)             8320      
                                                                 
 time_distributed (TimeDistr  (None, 4, 11)            363       
 ibuted)                                                         
                                                                 
Total params: 14,315
Trainable params: 14,315
Non-trainable params: 0
_________________________________________________________________
[98.63 97.85 97.56 95.25 91.61]
[98.45 96.98 96.37 93.   88.82]
