In [1]:
import numpy as np
import pandas as pd
#dataset import
df = pd.read_csv("../Data/data_8_nodes_yen.csv") #You need to change #directory accordingly
df.head()

X(1, 2)  X(1, 3)  X(2, 4)  X(2, 5)  X(3, 4)  X(3, 7)  X(4, 6)  X(5, 6)  \
0       10       40       30       50       30       20       20       10   
1       90       50       50       30       30       80       80       30   
2       10       60       80       50       40       50       30       90   
3       80       20       40       60       50       80       90       60   
4       20       70       50       40       20       70       80       80   

   X(5, 8)  X(6, 7)  ...  Y4(1, 3)  Y4(2, 4)  Y4(2, 5)  Y4(3, 4)  Y4(3, 7)  \
0       90       70  ...         0         1         0         0         0   
1       30       80  ...         1         0         0         1         0   
2       80       30  ...         1         0         0         1         0   
3       80       80  ...         1         0         0         1         0   
4       10       10  ...         0         1         0         0         0   

   Y4(4, 6)  Y4(5, 6)  Y4(5, 8)  Y4(6, 7)  Y4(7, 8)  
0         1         0         0         1         1  
1         1         1         1         0         0  
2         1         0         0         1         1  
3         1         1         1         0         0  
4         1         1         1         0         0  

[5 rows x 55 columns]

In [2]:
edges = [[1, 2], [1, 3], [2, 4], [2, 5], [3, 4], [3, 7], [4, 6], [5, 6], [5, 8], [6, 7], [7, 8]]

In [3]:
number_edges = 11
number_steps = 4
start_node = 1
end_node = 8

In [4]:
X = df.iloc[:,:number_edges].values
y = df.iloc[:,number_edges:].values

In [5]:
X.shape

(100000, 11)

In [6]:
y.shape

(100000, 44)

In [7]:
from sklearn.model_selection import train_test_split
X1,X2,y_train,y_test = train_test_split(X,y,test_size = 0.1)

In [8]:
X2[1]

array([30, 20, 60, 80, 90, 70, 80, 50, 40, 70, 50], dtype=int64)

In [9]:
y_test[1]

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
      dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X1)
X_test= sc.fit_transform(X2)

In [11]:
y_train[0]

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0],
      dtype=int64)

In [12]:
X2[1,:]

array([30, 20, 60, 80, 90, 70, 80, 50, 40, 70, 50], dtype=int64)

In [13]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
# Neural network
model = Sequential()
model.add(Dense(256, input_dim=number_edges, activation="relu"))
model.add(Dense(256, activation="relu"))
model.add(Dense(number_steps*number_edges, activation="sigmoid"))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               3072      
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dense_2 (Dense)             (None, 44)                11308     
                                                                 
Total params: 80,172
Trainable params: 80,172
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss='BinaryCrossentropy', optimizer='adam')

In [16]:
model.fit(X_train, y_train, epochs=100, batch_size=64)

Epoch 1/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.3310
Epoch 2/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.2333
Epoch 3/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1994
Epoch 4/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1798
Epoch 5/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1659
Epoch 6/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1559
Epoch 7/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1478
Epoch 8/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1412
Epoch 9/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1358
Epoch 10/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1308
Epoch 11/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.1269
Epoch 12/100
1407/1407 [==============================] - 3s 2ms/step - lo

1407/1407 [==============================] - 2s 2ms/step - loss: 0.0578
Epoch 98/100
1407/1407 [==============================] - 3s 2ms/step - loss: 0.0574
Epoch 99/100
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0572
Epoch 100/100
1407/1407 [==============================] - 2s 2ms/step - loss: 0.0565


In [17]:
len(model.layers)

3

In [18]:
pred=model.predict(X_train)

2813/2813 [==============================] - 3s 1ms/step


In [19]:
pred.shape

(90000, 44)

In [20]:
y_train_2 = np.reshape(y_train,(y_train.shape[0], number_steps, number_edges))

In [21]:
y_train_2.shape

(90000, 4, 11)

In [22]:
pred = np.reshape(pred,(pred.shape[0], number_steps, number_edges))

In [23]:
pred[0]

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 7.48834169e-38, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 3.54312192e-35],
       [2.08717521e-18, 1.00000000e+00, 0.00000000e+00, 2.37860044e-15,
        8.68379646e-34, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        8.22406850e-19, 0.00000000e+00, 1.00000000e+00],
       [2.44776110e-08, 1.00000000e+00, 1.18226936e-07, 6.21325356e-08,
        9.95813072e-01, 4.91354056e-03, 9.99908805e-01, 6.93278313e-02,
        9.15567577e-02, 9.99987602e-01, 9.07983005e-01],
       [2.11808674e-05, 9.99979556e-01, 1.02367976e-05, 1.26179145e-03,
        5.78261986e-02, 9.62252200e-01, 2.31817588e-02, 8.91174853e-01,
        9.09329772e-01, 9.99918580e-01, 9.55360159e-02]], dtype=float32)

In [24]:
import copy
def cost_path(x,y):
    cost = 0
    path = []
    for i in range(number_edges):
        if y[i]==1:
            path.append(edges[i])
            cost+= x[i]
    if(len(path)!=0):
        path_2 = copy.deepcopy(path)
        path_nodes = [start_node]
        if(path[0][0]!=start_node):
            cost = 0
        else:
            path_nodes.append(path[0][1])
            del path_2[0]
            condition = True
            while(len(path_2)!=0 and condition):
                condition = False
                for i in range(len(path_2)):
                    if(path_nodes[-1] in path_2[i]):
                        path_2[i].remove(path_nodes[-1])
                        path_nodes.append(path_2[i][0])
                        path_2.pop(i)
                        condition = True
                        break
        if(path_nodes[-1]!=end_node or len(path_2)!=0):
            cost = 0
    else:
        cost = 0
    return cost

In [25]:
cost_path(X1[1],y_train[1])

120

In [26]:
accuracy = np.zeros(number_steps+1)
for i in range(pred.shape[0]):
    condition_1 = True
    for t in range(number_steps):
        output = copy.deepcopy(pred[i][t])
        condition_2 = True
        for j in range(len(output)):
            output[j] = round(output[j])
        if(cost_path(X1[i],output) != cost_path(X1[i],y_train_2[i][t])):
            condition_2 = False
            condition_1 = False
        if condition_2:
            accuracy[t] += 1
    if condition_1:
        accuracy[number_steps] += 1
accuracy = np.round(accuracy / pred.shape[0] * 100,2)
accuracy

array([99.67, 95.85, 87.55, 71.98, 65.87])

In [27]:
pred_test=model.predict(X_test)

313/313 [==============================] - 0s 1ms/step


In [28]:
y_test_2 = np.reshape(y_test,(y_test.shape[0], number_steps, number_edges))
y_test_2.shape

(10000, 4, 11)

In [29]:
pred_test = np.reshape(pred_test,(pred_test.shape[0], number_steps, number_edges))

In [30]:
accuracy_test = np.zeros(number_steps+1)
for i in range(pred_test.shape[0]):
    condition_1 = True
    for t in range(number_steps):
        output = copy.deepcopy(pred_test[i][t])
        condition_2 = True
        for j in range(len(output)):
            output[j] = round(output[j])
        if(cost_path(X1[i],output) != cost_path(X1[i],y_test_2[i][t])):
            condition_2 = False
            condition_1 = False
        if condition_2:
            accuracy_test[t] += 1
    if condition_1:
        accuracy_test[number_steps] += 1
accuracy_test = np.round(accuracy_test / pred_test.shape[0] * 100,2)
accuracy_test

array([99.16, 94.1 , 84.76, 68.52, 61.74])

In [31]:
model.summary()
print(accuracy)
print(accuracy_test)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               3072      
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dense_2 (Dense)             (None, 44)                11308     
                                                                 
Total params: 80,172
Trainable params: 80,172
Non-trainable params: 0
_________________________________________________________________
[99.67 95.85 87.55 71.98 65.87]
[99.16 94.1  84.76 68.52 61.74]
